### ISSUE TITLE
Social Login Integration

### ISSUE THREAD

**Issue by vrijmetse** [furaiev/amazon-cognito-identity-dart-2#115]
I have been using this plugin with `https://pub.dev/packages/webview_flutter` to enable Social Login which works just fine. 
However if I compare with other apps on my phone which also provide Social Login, the user experience / on-boarding is not as smooth. 

There's one process which annoys me the most, I have to key in my username / password in the browser to login to Facebook / Google during fresh app installation. I don't think this should be this way, since my Facebook / Google account is already logged in in the device.

What am I missing here?

Can we even integrate this plugin with `https://pub.dev/packages/flutter_facebook_auth` and `https://pub.dev/packages/google_sign_in` ?

**Comment by furaiev** [comment]
Take a look at 
https://pub.dev/packages/firebase_auth
https://pub.dev/packages/flutter_facebook_login
https://pub.dev/packages/flutter_facebook_auth

**Comment by vrijmetse** [comment]
Does it mean I cant use aws cognito anymore ?

**Comment by furaiev** [comment]
You can use Cognito, but it doesn't have direct integration with the FB app or firebase. So, when you open the browser it doesn't know if you have installed these apps and if you are already logged in.

**Comment by sergiofigueras** [comment]
Thanks for the info. Is there any workaround for it?

**Comment by furaiev** [comment]
I'm not sure. You can add more details and open an issue at Github.

чт, 14 янв. 2021 г. в 22:30, Sergio Figueras <notifications@github.com>:

**Comment by vrijmetse** [comment]
Hi @furaiev,

Not sure if I misunderstood this but I found this in one of the comment in this [SO question](https://stackoverflow.com/questions/61160027/cannot-figure-out-how-to-setup-aws-cognito-for-google-sign-in-in-a-flutter-app).

The comment is 

`It's using google login with a separate package and get the id_token out of it. Then, use the openId token in Identity Credential`

And I tried the following with Google sign in plugin

```
Future<CognitoCredentials> getAwsCredentialsForGoogle() async {
    credentials = CognitoCredentials(_identityPoolId, _userPool);
    final GoogleSignIn googleSignIn = GoogleSignIn(scopes: ['email']);
    final GoogleSignInAccount googleSignInAccount = await googleSignIn.signIn();
    GoogleSignInAuthentication googleSignInAuthentication = await googleSignInAccount.authentication;
    await credentials.getAwsCredentials(googleSignInAuthentication.idToken, "accounts.google.com");
    return credentials;
  }
```

However I notice the credentials contains some info such as `accessKeyId` , `secretAccessKey`, and `sessionToken` but not `JwtToken` . What am I missing here?

**Comment by alextarrago** [comment]
Any workaround on this? @furaiev

**Comment by furaiev** [comment]
@alextarrago unfortunately I don't know if there is a workaround. I don't use Cognito for a long time. You are welcome to investigate this issue and contribute changes (if any needed).
