### ISSUE TITLE
Forgot password issue

### ISSUE THREAD

**Issue by sanalkv** [furaiev/amazon-cognito-identity-dart-2#116]
forgot password doesn't throw exception if cognito user doesn't exist. How to verify whether the user exist during forgot password ?

**Comment by furaiev** [comment]
Hi @sanalkv,
I believe that it is not secure checking if the user exists or not.
It's better to inform the user that `the recovered password was sent if the user exists`. 

Otherwise, someone can easily go through the list of emails and filter exists users.

**Comment by sanalkv** [comment]
If someone wants to go through the list of emails and filter existing users then they can just use signup because it will return user already exist error if user exist exist in database, so if anyone wants to check whether a user exist they have still have the option. So i don't think adding the condition to forgot password would create any kind of problem.

**Comment by furaiev** [comment]
As soon as this package is based on [amazon-cognito-identity-js]( https://github.com/aws/aws-amplify/tree/master/packages/amazon-cognito-identity-js), you are welcome to create an issue there.

In case this feature will be added in official aws-amplify, it can be added here as well.

**Comment by sanalkv** [comment]
Sure, thanks for the info.
