### ISSUE TITLE
S3 upload PUT signature error

### ISSUE THREAD

**Issue by ThinkTransit** [furaiev/amazon-cognito-identity-dart-2#120]
Hi all,

Apologies for posting here as I don't believe this is an issue however I have been struggling with this for a few days and I'm hoping someone can help.

I'm trying to upload text files to S3 from a flutter app using a http PUT. I have tested it through POSTMAN and it works ok so I'm confident my AWS credentials are ok.

I'm using the code below however I always get a signature error

```
The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Code:

```dart
////////////////////////////////////////////////////////////
  final awsSigV4Client = AwsSigV4Client(
    'XXXXXXXXXXXXXX', 'XXXXXXXXXXXX', 'https://XXXXXXX.s3.amazonaws.com/test.txt',
      serviceName: 's3',
 //     //sessionToken: credentials.sessionToken,
      region: 'ap-southeast-1',
      defaultContentType: 'text/plain', );


  final signedRequest = SigV4Request(awsSigV4Client,
      method: 'PUT',
      path: '/test.txt',
      headers: Map<String, String>.from(
          {'Content-Type': 'text/plain', 'Content-Length': "6", 'x-amz-content-sha256': SigV4.hexEncode(SigV4.hash(utf8.encode("test"))), }),
      body: "test"
      );
print(signedRequest.headers);
  http.Response response;
  try {
    response = await http.put('https://xxxxxxx.s3.amazonaws.com/test.txt',
        headers: signedRequest.headers, body: signedRequest.body);
  } catch (e) {
    print(e);
  }
  print(response.body);

  ///////////////////////////////////////////////////////

```

Does anyone have any ideas?

Thanks

**Comment by furaiev** [comment]
Try to change the content type to `'Content-Type': 'application/graphql; charset=utf-8'`

**Comment by ThinkTransit** [comment]
Thanks for the suggestion, unfortunately it still gives me the same signature error.

**Comment by ThinkTransit** [comment]
> @ThinkTransit did you find any solution for that issue?

@demsey2 No unfortunately I couldn't get it working so I used a different approach for uploading files.
