### ISSUE TITLE
CognitoUser.authenticateUser() very slow on Flutter Web

### ISSUE THREAD

**Issue by CrisNegoianu** [furaiev/amazon-cognito-identity-dart-2#123]
Hello.

First, I'd like to talk you for your work. I found the library very useful.

On Flutter Web, the call to the CognitoUser.authenticateUser() is very slow (about 8 seconds).
When I compile the application for mobile, it runs very quickly. It only takes about 1-2 seconds. That's including the 2 round trips to AWS.

I've debugged it a little bit and narrowed it down to this method: modPow() of the AuthenticationHelper class.
Is anyone else experiencing this with Flutter Web?

Is there any chance this method can be reviewed to see if it's performance can be improved on web?
Maybe an option would be to make a call to javascript, for this method when running on web, and using the implementation from amplify js. I would explore this myself, but my Flutter skills are not good enough for that.

Appreciate your efforts.

Kind regards,
Cris

**Comment by mat100payette** [comment]
I can confirm `modPow()` is taking very long on my end too

**Comment by furaiev** [comment]
Hi guys, unfortunately, I didn't use it on the web.
You are welcome to investigate the issues and contribute fixes.

**Comment by mat100payette** [comment]
@furaiev I have got a fix, but it's not something I can make a pull request for sadly. It involves a pretty nasty setup with web workers to offload the heavy computation of the `modPow` function. That forces the dev to compile his own worker using dart2js.

If I ever make this process cleaner (which I doubt I even can) I'll let you know.

**Comment by mat100payette** [comment]
@furaiev Although it wouldn't be parallel, would it be possible to make `modPow` async so it doesnt hog the main thread ?

**Comment by clinsign** [comment]
I did some digging into the origin of this issue - 
https://github.com/dart-lang/sdk/issues/32626#issuecomment-375070404

**Comment by blattr** [comment]
I am facing the same problem. Authenticating an user (on web) is very slow and also blocking the main thread. I really love this plugin and this issue is not the mother of all problems but it is indeed a pretty bad user experience :)

**Comment by mat100payette** [comment]
@blattr I have a nasty fix, but it works (fully parallel). If you desperately need it, lemme know where I can contact you and I'll provide the solution (it's too lenghty and ugly to put here).

**Comment by blattr** [comment]
@mat100payette first of all, thanks for the reply. I would highly appreciate "a look" on your fix :) Please feel free to contact me by email (it is now showing in my profile).

**Comment by akshitverma8191** [comment]
Hi I'm using this package in flutter, Sign up is working fine with confirming the user, but authentication is throwing the error:

CognitoClientException{statusCode: 400, code: NotAuthorizedException, name: NotAuthorizedException, message: Unable to verify secret hash for client  ************************}

I have given the client secret in both userpool and cognitouser.
Please help me.

**Comment by furaiev** [comment]
@akshitverma8191 here is a thread for your issue https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/99

**Comment by bobbyqul** [comment]
i am also interested in your fix

**Comment by CrisNegoianu** [comment]
I would also like to have a look at the fix.
Is it worth putting in a just, so anyone can have a look?
Thank you.

**Comment by mat100payette** [comment]
@bobbyqul , @CrisNegoianu I cannot put it here as it is too large and requires a few files and explanation. I'd be glad to send it by email. Just send me a message at matpayette@hotmail.com.

**Comment by furaiev** [comment]
@mat100payette I believe it would be nice if you create a small repo or gist for your solution and share link/links :)

**Comment by mat100payette** [comment]
@furaiev Here's a quick one then. Cleaned it up a little, but that's all the effort I'm willing to spend on such a convoluted solution for now.

https://gist.github.com/mat100payette/16deb6a708537606493ff074104a94f7

**Comment by Krystian95** [comment]
+1

**Comment by Lock128** [comment]
Thanks for the potential fix @mat100payette  - as Flutter on Web is now stable (and I am using it in a new project) - @furaiev how can we help to make this "fix" (or smth similar) part of your plugin?

**Comment by Lock128** [comment]
Can' t se just fix this by going back to the official implementation of modPow, @furaiev ?

See PR here: https://github.com/furaiev/amazon-cognito-identity-dart-2/pull/149

**Comment by mat100payette** [comment]
> Can' t se just fix this by going back to the official implementation of modPow, @furaiev ?
> 
> See PR here: #149

Have you tested it ? I had already tried that and on my end, it was still a CPU hog, freezing the UI.

**Comment by Lock128** [comment]
Well, I tested login a few times and it seemed to behave better/faster.
Here Chrome DevTools Profiler information, BEFORE the change:
![image](https://user-images.githubusercontent.com/327276/117022189-51d96280-acf8-11eb-8a5f-f072dab6a5c2.png)


And now AFTER the change:
![image](https://user-images.githubusercontent.com/327276/117022236-5d2c8e00-acf8-11eb-92a4-5376ed01caaf.png)



Looks promising but I think further testing should be done to confirm its better now.

**Comment by Lock128** [comment]
This PR https://github.com/furaiev/amazon-cognito-identity-dart-2/pull/149 has been merged and is now part of version 1.0.3 of the plugin - feel free to test @mat100payette  and let me know if you get any problems.

**Comment by Lock128** [comment]
The "fix" (going back to the standard implementation of BigInt.modPow) did not improove the performance for me a lot, unfortunately. 
We will need to look more detailed into how to resolve this....

**Comment by mat100payette** [comment]
@Lock128 Yeah as far as I remember, when I had tested it, it wasn't that much faster.

**Comment by ryanboerner** [comment]
+1

**Comment by Johannes0Horn** [comment]
I'm also having issues with web UI hanging while this operation completes.

**Comment by DriftingShadows** [comment]
Prominent issue on flutter web it seems.

**Comment by metafounder** [comment]
I am also interested in a fix for this

**Comment by Lock128** [comment]
I think this is behaving even slower than before in the newest Flutter/Dart version as far as I see it...

**Comment by Lock128** [comment]
Given the "Amplify Flutter" is not available on Web yet (see https://github.com/aws-amplify/amplify-flutter/issues/234#issuecomment-1010349552) this is still a major issue as far as I see it

**Comment by konectech** [comment]
As this is a flutter web issue, I came up with a workaround to make an external JavaScript call to do the modPow calculation using the native BigInt type. I have included it here if anyone else would like to use it.

It uses a conditional import to load a platform version of the modPow method. The web version uses package:js to call out the JavaScript method that will perform the calculation. String versions of the BigInts are passed to and from the JavaScript method.

Include package:js as a dependency in _pubspec.yaml_
`js: 0.6.3`

Add the abstracted platform versions of the modPow method. Base and mobile are the same.
New files _big_int_modpow_base.dart_ and _big_int_modpow_mobile.dart_
```
BigInt modPow(BigInt? b, BigInt e, BigInt? m) {
    if (b != null && m != null) {
      return b.modPow(e, m);
    }
    return BigInt.one;
  }

```
The web version includes the package:js annotations.
New file _big_int_modpow_web.dart_
```
@JS()
library bigint_modpow;

import 'package:js/js.dart';

@JS('jsBigIntModPow')
external String jsBigIntModPow(String b, String e, String m);

BigInt modPow(BigInt? b, BigInt e, BigInt? m) {
    if (b != null && m != null) {
      try {        
        return BigInt.parse(jsBigIntModPow(b.toString(), e.toString(), m.toString()));
      } on NoSuchMethodError {
        return b.modPow(e, m);
      }       
    }
    return BigInt.one;
  }
```

Remove the modPow method from _authentication_helper.dart_ and perform the conditional import
```
import 'big_int_modpow_base.dart'
  if (dart.library.io) 'big_int_modpow_mobile.dart'
  if (dart.library.html) 'big_int_modpow_web.dart';
```

Lastly include the JavaScript method in your top level _index.html_ page for you web flutter app.
```
<script>
  function jsBigIntModPow(bStr, eStr, mStr) {
    let b = BigInt(bStr);
    let e = BigInt(eStr);
    let m = BigInt(mStr);
    let bigIntOne = BigInt(1);
    let bigIntZero = BigInt(0);
    if (e < bigIntOne) {
      return bigIntOne;
    }
    if (b < bigIntZero || b > m) {
      b = b % m;
    }
    var r = bigIntOne;
    while (e > bigIntZero) {
      if ((e & bigIntOne) > bigIntZero) {
        r = (r * b) % m;
      }
      e = e >> bigIntOne;
      b = (b * b) % m;
    }
    return r;
  }
</script>
```

I had to include package:js to the pubspec.yaml of the top level app as well.

**Comment by Lock128** [comment]
Wowo, @konectech - that looks great.


now we only a possiblity to include this "fix" as part of the open source dart package.

**Comment by jay-mtl** [comment]
Thanks a lot @konectech , you save my life and +1 to add this to the open source package.

**Comment by Drkstr** [comment]
Thanks for the awesome fix @konectech. 

@Lock128 , @furaiev do a timeline of when this will be merged into the dart package? 
(defiantly a nice to have and not a requirement :) )

**Comment by JaredEzz** [comment]
> As this is a flutter web issue, I came up with a workaround to make an external JavaScript call to do the modPow calculation using the native BigInt type. I have included it here if anyone else would like to use it.
> 
> It uses a conditional import to load a platform version of the modPow method. The web version uses package:js to call out the JavaScript method that will perform the calculation. String versions of the BigInts are passed to and from the JavaScript method.
> 
> Include package:js as a dependency in _pubspec.yaml_ `js: 0.6.3`
> 
> Add the abstracted platform versions of the modPow method. Base and mobile are the same. New files _big_int_modpow_base.dart_ and _big_int_modpow_mobile.dart_
> 
> ```
> BigInt modPow(BigInt? b, BigInt e, BigInt? m) {
>     if (b != null && m != null) {
>       return b.modPow(e, m);
>     }
>     return BigInt.one;
>   }
> ```
> 
> The web version includes the package:js annotations. New file _big_int_modpow_web.dart_
> 
> ```
> @JS()
> library bigint_modpow;
> 
> import 'package:js/js.dart';
> 
> @JS('jsBigIntModPow')
> external String jsBigIntModPow(String b, String e, String m);
> 
> BigInt modPow(BigInt? b, BigInt e, BigInt? m) {
>     if (b != null && m != null) {
>       try {        
>         return BigInt.parse(jsBigIntModPow(b.toString(), e.toString(), m.toString()));
>       } on NoSuchMethodError {
>         return b.modPow(e, m);
>       }       
>     }
>     return BigInt.one;
>   }
> ```
> 
> Remove the modPow method from _authentication_helper.dart_ and perform the conditional import
> 
> ```
> import 'big_int_modpow_base.dart'
>   if (dart.library.io) 'big_int_modpow_mobile.dart'
>   if (dart.library.html) 'big_int_modpow_web.dart';
> ```
> 
> Lastly include the JavaScript method in your top level _index.html_ page for you web flutter app.
> 
> ```
> <script>
>   function jsBigIntModPow(bStr, eStr, mStr) {
>     let b = BigInt(bStr);
>     let e = BigInt(eStr);
>     let m = BigInt(mStr);
>     let bigIntOne = BigInt(1);
>     let bigIntZero = BigInt(0);
>     if (e < bigIntOne) {
>       return bigIntOne;
>     }
>     if (b < bigIntZero || b > m) {
>       b = b % m;
>     }
>     var r = bigIntOne;
>     while (e > bigIntZero) {
>       if ((e & bigIntOne) > bigIntZero) {
>         r = (r * b) % m;
>       }
>       e = e >> bigIntOne;
>       b = (b * b) % m;
>     }
>     return r;
>   }
> </script>
> ```
> 
> I had to include package:js to the pubspec.yaml of the top level app as well.

@konectech do you have a fork of this repo with this implemented?

**Comment by JaredEzz** [comment]
@Lock128 I created a pull request with the aforementioned fixes and updated documentation in README https://github.com/furaiev/amazon-cognito-identity-dart-2/pull/186

**Comment by furaiev** [comment]
@JaredEzz thank you for your PR! 
Guys, you are welcome to test the latest 2.0.0 version.

**Comment by JaredEzz** [comment]
Took my login times from an average of 12.46 seconds to 0.6064 seconds

**Comment by MurtuzaSrashtaSoft** [comment]
this is not working in release mode.

i build my application in release mode by using below command.

`flutter run -d chrome --release -t lib/main.dart`

but throw error(null) not able to login.
