### ISSUE TITLE
Null Safety support

### ISSUE THREAD

**Issue by jlubeck** [furaiev/amazon-cognito-identity-dart-2#126]
Hey, as Flutter is quickly adopting null safety across the board, are you planning on supporting it here?

I ran into an issue in one of my apps where I had to start updating packages for null safety support, and when I got to this one, I got stuck. Because even though I can override the `http` dependency to not get errors during `pub get`, I get them at compile time because apparently `http` made a change in some of their methods and now they take `Uri` instead of `String`.

So this library is no longer compatible with `http 0.13.0`.

**Comment by furaiev** [comment]
Hey @jlubeck 
you can try to test https://pub.dev/packages/amazon_cognito_identity_dart_2/versions/1.0.0-nullsafety.0

**Comment by mat100payette** [comment]
This should be fixed now I believe ?
https://pub.dev/packages/amazon_cognito_identity_dart_2/versions/1.0.0-nullsafety.2
