### ISSUE TITLE
Nullsafety breaks login

### ISSUE THREAD

**Issue by mat100payette** [furaiev/amazon-cognito-identity-dart-2#127]
Tried upgrading to `1.0.0-nullsafety.0` but the login broke.

Going into `authenticateUser`, then `_authenticateUserDefaultAuth(...)`, I see that `data = await client!.request('InitiateAuth', await _analyticsMetadataParamsDecorator.call(params));` throws with the following:

> CognitoClientException: Cognito client request error with unknown message

The same code works using `0.1.25+1`.

**Comment by furaiev** [comment]
Thanks for reporting @mat100payette ,
`1.0.0-nullsafety.0` wasn't actually tested yet and can contain errors.

If you have some time please investigate and contribute.

**Comment by zelliot** [comment]
The problem is with the `http.post` in client.dart. It parses the URL incorrectly. The package needs to use `Uri.parse`, which doesn't work with `String?`.

**Comment by furaiev** [comment]
Hey @zelliot ,
Thanks, please try `1.0.0-nullsafety.1`

**Comment by zelliot** [comment]
Unfortunately still not working. I left a comment on the commit.

You need to change Line 45 to `Uri.parse(endpointReq!),`

**Comment by furaiev** [comment]
@zelliot plz try `1.0.0-nullsafety.2`

**Comment by zelliot** [comment]
Works perfectly now. Thanks @furaiev!

**Comment by mat100payette** [comment]
I confirm that this has been fixed. Thanks.
