### ISSUE TITLE
Inconsistent cache key  using in get/set session

### ISSUE THREAD

**Issue by dgofman** [furaiev/amazon-cognito-identity-dart-2#129]
Please fix the session key in your cognito_user.dart. 

Get defined a key as:
" 'CognitoIdentityServiceProvider.${pool.getClientId()}.$username';"
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/master/lib/src/cognito_user.dart#L176

Set define a key as:
'CognitoIdentityServiceProvider.${pool.getClientId()}';
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/master/lib/src/cognito_user.dart#L1030

I am suggesting creating a getter
String get keyPrefix => 'CognitoIdentityServiceProvider.${pool.getClientId()}.$username';

and replace in your code:

https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/master/lib/src/cognito_user.dart#L176
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/master/lib/src/cognito_user.dart#L249
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/master/lib/src/cognito_user.dart#L324
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/master/lib/src/cognito_user.dart#L1030
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/master/lib/src/cognito_user.dart#L1051
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/master/lib/src/cognito_user.dart#L1070
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/master/lib/src/cognito_user.dart#L1084

**Comment by furaiev** [comment]
@dgofman you are welcome to contribute and create PR.

**Comment by dgofman** [comment]
@furaiev I found one more issue. Check my changes https://github.com/furaiev/amazon-cognito-identity-dart-2/pull/130

**Comment by dgofman** [comment]
@furaiev Hi Alex, Do you have any idea how can I use session credentials for sending the requests using SSM/ S3 APIs?
I believe you should return: accessKeyId, secretAccessKey and sessionToken
logMessage('AWS Access Key: '+ AWS.config.credentials.accessKeyId);
logMessage('AWS Secret Key: '+ AWS.config.credentials.secretAccessKey);
logMessage('AWS Session Token: '+ AWS.config.credentials.sessionToken);

https://1billiontech.com/blog_User_Authentication_and_Authorization_with_AWS_Cognito.php
