### ISSUE TITLE
remove keyword 'new' from the code, isn't needed in dart 2

### ISSUE THREAD

**Issue by aidandavis** [furaiev/amazon-cognito-identity-dart-2#13]
and it's recommended against

**Comment by furaiev** [comment]
Closed by [0d52a9e](https://github.com/furaiev/amazon-cognito-identity-dart-2/commit/0d52a9e9429bd33d1c66e2e4387e3c4599a8a84d)

**Comment by aidandavis** [comment]
nothing in that linked PR adresses this issue

**Comment by furaiev** [comment]
link is updated

**Comment by aidandavis** [comment]
Nice :) thanks for keeping this package going, by the way.
