### ISSUE TITLE
Retrieving data from Storage as FutureOr<String?> breaks clients

### ISSUE THREAD

**Issue by pal** [furaiev/amazon-cognito-identity-dart-2#133]
As I was migrating the example app to null-safety, I had to also remote the casts done when reading from Storage. 

Simply removing the casts worked wonders. 

I will supply a PR for this. Think it would make sense to unless there is some case where this cast is needed that I'm unaware of.

Thanks!

**Comment by furaiev** [comment]
Thank you, I’ll review on Sunday-Monday

**Comment by jlubeck** [comment]
I just tried #134 and verified it fixed this same issue I was having. Thank you @pal

**Comment by furaiev** [comment]
please check `1.0.0-nullsafety.3`
