### ISSUE TITLE
How to use OTP login via this?

### ISSUE THREAD

**Issue by gauravmehta13** [furaiev/amazon-cognito-identity-dart-2#141]
Is otp login and signup available?

**Comment by Aathi** [comment]
@gauravmehta13 Yes it is.

try this
STEP - 1
```dart
 Future login(String phone) async {
    String _phone = phone.substring(1);
    String finalPhone = "+44$_phone";

    _cognitoUser =new CognitoUser(finalPhone, _userPool, storage: _userPool.storage);
    final authDetails = new AuthenticationDetails(username: finalPhone, password: _password);

    try {
      _session = await _cognitoUser.authenticateUser(authDetails);
    } on CognitoUserMfaRequiredException catch (e) {
         // Once you received the OTP dont change the route
        setState(() {
          _isOTPRequired = yes;
          })
         // Show the otp enter page
        // Use the  otp verification method to validate otp
    } catch (e) {
      print(e);
    }
    print(_session.getAccessToken().getJwtToken());

    if (!_session.isValid()) {
      return null;
    }
  }
```

STEP - 2
```dart
Future otpVerification(String confirmationCode) async {

    try {
      _session = await _cognitoUser.sendMFACode(confirmationCode, 'SMS_MFA');
    } on CognitoClientException catch (e) {
      if (e.code == 'UserNotConfirmedException') {
      } else {
        throw e;
      }
    }


   // import 'package:get_storage/get_storage.dart';
   // Use "get_storage" storage to store all the required attributes
    final attributes = await _cognitoUser.getUserAttributes();
    box.write("id", attributes[0].getValue());
    box.write("name", attributes[2].getValue());
    box.write("phone_number", attributes[4].getValue());
    box.write("role", attributes[5].getValue());
    addToken(attributes);
  }
```

**Comment by gregorysaml** [comment]
Hello 
So i want to make a passwordless log in with sms and i am getting an error when i try this login function do i need a password variable
thanks in advance

**Comment by Aathi** [comment]
@gregorysaml  Yes you need,  It is not complete code.  You have to write your own service base on your requirement. In my case I am using a fixed password as a ENV variable, password is same for all the users.

**Comment by gregorysaml** [comment]
@Aathi thanks for the fast reply. Still i cant make it to work 
i get this error (CognitoClientException{statusCode: 400, code: NotAuthorizedException, name: NotAuthorizedException, message: Incorrect username or password.) 
idk if i have to create a user first but when i am trying t from the interface i get a lambda error .
So am i doing something wrong with my app clients set up ? do i have to use Lambda functions? Can you help me with the set up ? 
Thanks

**Comment by gregorysaml** [comment]
To make it clear 
 1) cognito set up 

- Atributes

![attributes](https://user-images.githubusercontent.com/73754387/115375915-e8753200-a1d6-11eb-9027-555e460e6f0c.png)

- MFA i have notice guides from 2020 can turn off MFA but i can't 

![Otp_multyfactor_settings](https://user-images.githubusercontent.com/73754387/115376508-6c2f1e80-a1d7-11eb-8ba0-d92e54e00710.png)

- App client set up 
![congito_otp_user_pool](https://user-images.githubusercontent.com/73754387/115377322-30e11f80-a1d8-11eb-85a2-f7ce56a07e81.png)
2) Lamdba (only the pre-sing-up triggers  ) 
pre sing up
![pre-sing-up](https://user-images.githubusercontent.com/73754387/115377811-a351ff80-a1d8-11eb-95ab-22aea07f25a3.png)
define auth challenge
![define-auth-challenge](https://user-images.githubusercontent.com/73754387/115377832-a816b380-a1d8-11eb-97f2-e9882ca5abcc.png)
create auth challenge
![create-auth-challenge](https://user-images.githubusercontent.com/73754387/115377841-a9e07700-a1d8-11eb-8ce2-d96d62a83bc0.png)
verify auth challenge
![verify-auth-challenge](https://user-images.githubusercontent.com/73754387/115378181-f3c95d00-a1d8-11eb-9dbc-f46e1ca8fa25.png)
3) This is the error that i am getting 
![otp_error1](https://user-images.githubusercontent.com/73754387/115378937-bca77b80-a1d9-11eb-9415-674b69e7f3c7.png)

**Comment by Aathi** [comment]
@gregorysaml 
This is the setup I have
<img width="1384" alt="Screenshot 2021-04-21 at 02 10 50" src="https://user-images.githubusercontent.com/5355180/115478648-e21e9e80-a246-11eb-9fa1-bb1d02035a3e.png">

In my case I haven't written any auth challenge. Just I wrote a user auto confirm lamda only.  Message will be handle automatically by cognito. I believe you have configured in different way. check the screenshot How I have managed to setup MFA

**Comment by gregorysaml** [comment]
@Aathi thank you , all those days i was trying to make it work,
Ι managed to register a user but now i am stuck trying to log in, idk if you got that error before 

![Screenshot from 2021-04-27 17-53-55](https://user-images.githubusercontent.com/73754387/116269518-f69ef180-a786-11eb-8bbe-428f2fdd11cc.png)

I also found out that i dont realy need all those lamdas just the pre-sing-up one or this one (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html)

**Comment by Aathi** [comment]
@you are almost there, This error means , it is waiting for the OTP. Catch the  exception ```MfaSetupRequiredException```
then write a function to verify the otp.  check the ```otpVerification``` https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/141#issuecomment-813703624

**Comment by gregorysaml** [comment]
Still getting the same error i tried to catch it and call otpverification but didnt work but i do receive an sms and sending back the code whitch i am receiving

```
  final authDetails =
        AuthenticationDetails(username: finalPhone, password: fixedPassword);
    try {
      _session = await _cognitoUser.authenticateUser(authDetails);
      isConfirmed = true;
    } on CognitoUserMfaRequiredException catch (e) {
      if (e.challengeName == 'SMS_MFA') {
        print(e);
        //should i call here otpver ? or when otpver is done should i pass something here ? 
      } else {
        print('$e not catch');
      }
    } on CognitoClientException catch (e) {
      if (e.code == 'UserNotConfirmedException') {
        isConfirmed = false;
      } else {
        throw e;
      }
    }

    if (!_session.isValid()) {
      print('notvalid');
    }
```
also getting this error too 

    
    
![error 2](https://user-images.githubusercontent.com/73754387/117326881-c0562600-ae9a-11eb-8866-e28fdb562d93.png)

Thanks for your time!

**Comment by udaysagartammina** [comment]
Hi, Anyone can help with phone number and otp based login examples. 

Thanks in Advance.

**Comment by Aathi** [comment]
@udaysagartammina  Try this, I have used different way make it work  however thats is not the right choice.  Try this article
https://itnext.io/passwordless-sms-authentication-backend-9932391c49dc

**Comment by aqueebqazi** [comment]
hello can you upload a complete code please I cannot find documentation for otp login kindly share thank you
