### ISSUE TITLE
Breaking change in v1.0.0 (Unhandled Exception)

### ISSUE THREAD

**Issue by zelliot** [furaiev/amazon-cognito-identity-dart-2#146]
Upgraded to v1.0.0 this morning and my existing code breaks when declaring a new CognitoUser object.

[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: LateInitializationError: Field 'storage' has already been initialized.
#0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:203:5)
#1      CognitoUserPool.storage=package:amazon_cognito_identity_dart_2/src/cognito_user_pool.dart:33
#2      new CognitoUser package:amazon_cognito_identity_dart_2/src/cognito_user.dart:70

**Comment by furaiev** [comment]
@zelliot thank you for the report.
Please check 1.0.1

**Comment by zelliot** [comment]
LGTM @furaiev. 
Thank you!
