### ISSUE TITLE
Can this be used Along side the Official Cognito Package?

### ISSUE THREAD

**Issue by fdarsot** [furaiev/amazon-cognito-identity-dart-2#159]
Hi there, 

I have a project set up that uses the official cognito package from the aws team, however they dont have the global sign out feature and i need to use that feature.

My Question is, can i use this package along side that one and just use this package for that global sign out feature?

What i want to achieve is, i only want 1 user to login to my app at 1 time, (cannot sign in from multiple devices with 1 account) (cannot have simultaneous sessions)

so i was going to call global signout before signing a user in.

please let me know if this would work!

**Comment by furaiev** [comment]
You can't easily do the global `signOut()` from this package. In order to do it, you should somehow be authenticated.
You can try to pass the session from the official package to this one, and if it's possible create a PR.
