### ISSUE TITLE
confirmRegistration is not sending clientSecret

### ISSUE THREAD

**Issue by lslv1243** [furaiev/amazon-cognito-identity-dart-2#16]
when I try to use confirmRegistration from CognitoUser I get the following error:
```
{
    "__type": "NotAuthorizedException",
    "message": "Unable to verify secret hash for client ***********"
}
```
then I debug the lib and figured it is not sending the client secret in this call, it can be fixed doing like the signUp method
```
if (_clientSecret != null) {
    params['SecretHash'] = CognitoUser.calculateClientSecretHash(username, _clientId, _clientSecret);
}
```

**Comment by furaiev** [comment]
It doesn't require the secret hash, just successfully checked payload
```
{
    ClientId: 6rit3uc1urc41gn7p3eb4e0iu3,
    ConfirmationCode: XXXXXX,
    Username: +XXXXXXXXX,
    ForceAliasCreation: false
}
```
I think that your error is misleading.
