### ISSUE TITLE
How I can refresh my access token?

### ISSUE THREAD

**Issue by VadimBliz** [furaiev/amazon-cognito-identity-dart-2#160]
Currently my session lives only 3 hours, my code to refresh it:

    try {
      CognitoUser? result = await _userPool.getCurrentUser();
      if (result == null || (await result.getSession()) == null) {
        final String? userEmail = await _getUserData('user_email');
        if (userEmail == null) {
          throw Exception();
        }
        result = CognitoUser(await _getUserData('user_email'), _userPool,
            clientSecret: FlutterConfig.get('CLIENT_SECRET') as String,
            storage: _storage)..setAuthenticationFlowType('REFRESH_TOKEN_AUTH');
        await result.getSession();
      }
      return result;
    } on Exception {
      throw Exception('error_7');
    }

**Comment by furaiev** [comment]
It seems like the same https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/18

**Comment by VadimBliz** [comment]
@furaiev Thank you for pointing this out, but after I tried it, I've got error "Client 3536dcc74jvtpbqtdbabbk**** is configured for secret but secret was not received"

**Comment by furaiev** [comment]
`"Client 3536dcc74jvtpbqtdbabbk**** is configured for secret but the secret was not received".` try to debug what data is inside your request.

`"Unable to verify secret hash for client 3536dcc74jvtpbqtdbabbkgdi7"` - can't be a result of caching. It is most probably an error from the server. (Maybe missed await for one of the previous Futures).

**Comment by VadimBliz** [comment]
Thank you for your answers, but you probably misunderstood me, "Unable to verify secret hash for client" error was appeared when I'm trying to get users session when app is launching

 result = CognitoUser(await _getUserData('user_email'), _userPool,
            clientSecret: FlutterConfig.get('CLIENT_SECRET') as String,
            storage: _storage);
         await result.getSession();
         
Also I tried to use  

 result = CognitoUser(await _getUserData('user_email'), _userPool,
            clientSecret: FlutterConfig.get('CLIENT_SECRET') as String,
            storage: _storage);
         await result..refreshSession(
        CognitoRefreshToken(
          await _getUserData('refresh_token'),
        ),
      );
      
'refresh_token' is the token that I previously cached on login with email and password

**Comment by VadimBliz** [comment]
I'm attaching full code here

[amazon_cognito.txt](https://github.com/furaiev/amazon-cognito-identity-dart-2/files/6768124/amazon_cognito.txt)

Note: this is a .dart file

**Comment by furaiev** [comment]
It seems like you need to use user's UUID (not the email) in this flow. https://forums.aws.amazon.com/thread.jspa?messageID=830794
