### ISSUE TITLE
Unable to verify secret hash

### ISSUE THREAD

**Issue by tejas2306** [furaiev/amazon-cognito-identity-dart-2#161]
/// Login user

_cognitoUser = CognitoUser(email, _userPool,
        storage: _userPool.storage, clientSecret: clientSecret);

    final authDetails = AuthenticationDetails(
      username: email,
      password: password,
    );

    bool isConfirmed;
    try {
      _session = await _cognitoUser.authenticateUser(authDetails);
      isConfirmed = true;
    } on CognitoClientException catch (e) {
      if (e.code == 'UserNotConfirmedException') {
        isConfirmed = false;
      } else {
        rethrow;
      }
    }

when i tried to login i am getting this exception

CognitoClientException{statusCode: 400, code: NotAuthorizedException, name: NotAuthorizedException, message: Unable to verify secret hash for client 2qb0o3ni38ge670t48dkkluk5r}

**Comment by furaiev** [comment]
please go through this topic https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/32
it seems like the same issue
