### ISSUE TITLE
Is there any way to confirm forgot password verification code before setting the new password?

### ISSUE THREAD

**Issue by emreakcan** [furaiev/amazon-cognito-identity-dart-2#162]
Currently forgot password flow  works as 
`cognitoUser.confirmPassword('verificationCode', 'newPassword');`
which gets the code and the password together, I want to confirm the code and then redirect to set password page, is that possible?

**Comment by furaiev** [comment]
I don't think it is possible.
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ConfirmForgotPassword.html

**Comment by emreakcan** [comment]
thank you @furaiev closing the question
