### ISSUE TITLE
Not Authorized Exception when trying to get session using refresh token

### ISSUE THREAD

**Issue by ashutosh2014** [furaiev/amazon-cognito-identity-dart-2#164]
Hi, 
I trying to get session using refresh token. In AppClient, Client secret is configured.
And also I passed client secret value as show below

```
    final congnitoUser = CognitoUser(email, userPool,
      clientSecret: backendConstants.aws_cognito_client_scret_hash);
try {
await congnitoUser.refreshSession(CognitoRefreshToken(token))
}
```

But I m getting this error -

> CognitoClientException{statusCode: 400, code: NotAuthorizedException, name: NotAuthorizedException, message: Client ** is configured for secret but secret was not received.

**Comment by furaiev** [comment]
it seems like a duplication of https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/160
