### ISSUE TITLE
Got User Confirmation Necessary error when a user logs in for the first time

### ISSUE THREAD

**Issue by benedict1986** [furaiev/amazon-cognito-identity-dart-2#165]
Hi, I have the following code to sign in a user. The first time it always failed with the error message "User Confirmation Necessary" while if I click the login button again, it can be logged in successfully. I am using `amazon_cognito_identity_dart_2: ^1.0.3` in my flutter project. I have checked the user status in cognito and the user is confirmed already. Can you please help to debug this piece of code.
```
    SignIn(String password, void Function(String, String) onSuccess, Future<void> Function(String) onFailure) async {
    var authDetails = new AuthenticationDetails(username: _cognitoUser!.username, password: password);
    try {
      _session = await _cognitoUser!.authenticateUser(authDetails);
      if (_session == null) {
        onFailure('Fail to login');
      }
      if (_notifyListeners != null) {
        _notifyListeners!.call();
      }
      _isEmailVerified = _session!.idToken.payload['email_verified'] ?? false;
      onSuccess(_session!.accessToken.getSub()!, (await getEmail())!);
    } on CognitoClientException catch (e) {
      await onFailure(e.message ?? 'Fail to sign in due to unknown reason.');
    } catch (e) {
      await onFailure(e.toString());
    }
  }
```

**Comment by furaiev** [comment]
Hi, the UserNotConfirmedException is thrown when a user is not confirmed successfully.
Most probably there is something in your AWS account settings.

**Comment by benedict1986** [comment]
Hi @furaiev , very sorry that I forgot to update my response. The situation at the moment is when I click the login button for the first time, I got the exception. Then I click the login button again and there is not exception.  

Let me double check my configuration. Also let me try to create a reproducible code and attach to this thread.

Thanks heaps

**Comment by razrinn** [comment]
Hi @furaiev , I'm currently facing the same problem with @benedict1986  related to `CognitoUserConfirmationNecessaryException` when trying to sign in for the first time after successfully creating and confirming an account. But, the error seems gone away when I tried to sign in again for the second time and so on. 

I'm using version 2.1.1. 

Thank you
