### ISSUE TITLE
Get "Invalid device key given" error when try to set new password fo user

### ISSUE THREAD

**Issue by CedSW** [furaiev/amazon-cognito-identity-dart-2#167]
Hi,
I'm trying to respond to CognitoUserNewPasswordRequiredException but `CognitoUser.sendNewPasswordRequiredAnswer(newPassword)` call always ends up with this error:

![image](https://user-images.githubusercontent.com/29180246/133740105-c15d79a1-5803-4a2e-84b4-1a9c407ca673.png)

I also checked the exception and there are no required attributes

**Comment by furaiev** [comment]
Hello,
Most probably we don't need to send `DEVICE_KEY ` in this request.
I can't check it as I don't use Cognito in my current projects and don't have an account.

You can try to remove these lines and try one more time
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/main/lib/src/cognito_user.dart#L813-L815

**Comment by CedSW** [comment]
That unfortunately didn't help, after the `await getCachedDeviceKeyAndPassword()` is `_deviceKey` still null, so removing those lines has no effect

**Comment by CedSW** [comment]
> Hello,
> Most probably we don't need to send `DEVICE_KEY ` in this request.
> I can't check it as I don't use Cognito in my current projects and don't have an account.
> 
> You can try to remove these lines and try one more time
> https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/main/lib/src/cognito_user.dart#L813-L815

the method, that is responsible for caching device key is never called, could that be the problem?

**Comment by furaiev** [comment]
I believe that it can. Try to call one of the methods that provide the DEVICE_KEY.
