### ISSUE TITLE
Null Safety error

### ISSUE THREAD

**Issue by luna-vasconcelos** [furaiev/amazon-cognito-identity-dart-2#169]
Hi, I'm trying to use the package for AWS API gateway and lambda function, but I'm getting a null safety error from the package itself, I'm using the last version of it and getting the following error when launching the app:

![image](https://user-images.githubusercontent.com/62728067/134360830-ea8e7f92-4863-4125-bd0a-a6314bd34db6.png)

**Comment by furaiev** [comment]
Hello,
Is your app a null safety?

**Comment by luna-vasconcelos** [comment]
Yes, it is

**Comment by furaiev** [comment]
Please add `flutter doctor -v` results

**Comment by luna-vasconcelos** [comment]
hey, i was able to make it work, inserting null checks in the source code on these two variables:
headers![x_amz_date] = datetime;
headers![x_amz_security_token] = awsSigV4Client.sessionToken;

so i changed both to be like this:
headers![x_amz_date] = datetime!;
headers![x_amz_security_token] = awsSigV4Client.sessionToken!;

since the only problem was the null safety, this did the work, can you check?

**Comment by furaiev** [comment]
could you please point the lines in the file? It seems like all is null safe.
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/main/lib/sig_v4.dart

**Comment by luna-vasconcelos** [comment]
yes, so, the lines that was returning the problem was 84 and 91, I think the problem was on the const amz_date and const amz_security_token, I think because they are both const, they could still return null but the other variables are on null safety, so when i added the null check with the "!" this solved the problem. I think that's what was happening
