### ISSUE TITLE
No API to refresh session and access token

### ISSUE THREAD

**Issue by drakebw** [furaiev/amazon-cognito-identity-dart-2#18]
There is not currently a way to refresh a user's session and their access token.

**Comment by furaiev** [comment]
Hi, 
`CongitoUser` has a method `refreshSession`

Something like:
```
session = await cognitoManager.cognitoUser.refreshSession(session.refreshToken);
```

**Comment by drakebw** [comment]
Thank you, I just barely found this when I forked it to add that functionality and came back to delete the issue. I was confused because it was implemented on the CognitoUser and not on the CognitoUserSession.
