### ISSUE TITLE
Pre-Signed URL to S3 Object download link

### ISSUE THREAD

**Issue by Lorenzohidalgo** [furaiev/amazon-cognito-identity-dart-2#183]
Hi,
I've been looking at the examples and was not able to figure out how/if I would be able to get a pre-signed download URL for an object stored in S3?

**Comment by cenezoic123** [comment]
Yeah, me too

Can't find a way to get the pre-signed URL using this package.

**Comment by nazarcybulskij** [comment]
@cenezoic123  I used this library https://pub.dev/packages/aws_auth  -- example code   https://gist.github.com/nazarcybulskij/a0ca2f12a93c22704a13bf2111d06a6f
