### ISSUE TITLE
Is CognitoMemoryStorage meant to persist user sessions?

### ISSUE THREAD

**Issue by JaredEzz** [furaiev/amazon-cognito-identity-dart-2#187]
SharedPreferences is an insecure way to store authenticated tokens or user session information because the Flutter Web implementation, shared_preferences_web, [just uses local storage. ](https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences_web/lib/shared_preferences_web.dart)

Local storage is unsuitable for storing authentication information, so I thought the CognitoMemoryStorage example referenced in the README was great. But this just stores information in a map.

Doesn't that map get cleared out when the app is restarted? So, in the case of a web app, any time the user closes and re-opens the tab or even refreshes? That is not persistent, which will not work to detect if a user session is still valid.

Am I misunderstanding this? Or is it just meant to work if you always have the web app open in a tab that never closes?

Also, this doesn't work for supporting multiple user pools, but that's another issue entirely.

**Comment by AndreiMisiukevich** [comment]
Yes, you are right. The default implementation of storage is just a map :)
If you need a secure way to store data you can write your own storage based on FlutterSecureStorage package (we did it for you project).

**Comment by JaredEzz** [comment]
I just used idb_shim which works great.
