### ISSUE TITLE
Platoforms support

### ISSUE THREAD

**Issue by AndreiMisiukevich** [furaiev/amazon-cognito-identity-dart-2#188]
Hello, Thanks for the great work!

I have a question. Does this plugin support all platforms which Flutter does (including web)?
I guess the answer is yes. But I want to confirm that, because pub.dev does not shows "WEB' label.

It would be great to update pub.dev description if Web is supported :)

<img width="869" alt="image" src="https://user-images.githubusercontent.com/10124814/164998198-5e5ab9d9-410e-4a93-ac42-c3aaf221ae0d.png">

Best Regards

**Comment by bentomania** [comment]
Hi @AndreiMisiukevich, yes it supports Web.  I haven't tested this on native Desktop platforms yet but I would be surprised if this doesn't work.

**Comment by AndreiMisiukevich** [comment]
I can confirm that it works pretty well on iOS, Android, Web, Windows and MacOS :)

Thanks again

**Comment by furaiev** [comment]
fixed in 2.1.0
