### ISSUE TITLE
Improve documentation - "Please note that this package is not production ready."

### ISSUE THREAD

**Issue by dtt101** [furaiev/amazon-cognito-identity-dart-2#19]
The README from the project mentions "Please note that this package is not production ready."

Is there a way we could understand why not? So that we could help contribute.

Thanks for all the hard work forking and updating the original project!

**Comment by furaiev** [comment]
Thank you for pointing, it's copy/paste mistake that will be removed with the nearest update.
I believe that a lot of developers use this package or its 1st version.

**Comment by dtt101** [comment]
@furaiev - thank you! Appreciate the clarification 👍
