### ISSUE TITLE
The provided example isn't up to date anymore

### ISSUE THREAD

**Issue by mailliwi** [furaiev/amazon-cognito-identity-dart-2#197]
Hi there,

Was trying to copy and paste the example provided with your package, and it seems that a lot of it is not working anymore?
All errors seem to be linked to null safety and types not being correct.
Anything I'm missing?

This is the case for the user model class, the user_service file and the storage file.

**Comment by furaiev** [comment]
The example works, there are `cognitoIdentityPoolId`, `apiEndpoint` and `awsRegion` should be provided.
I'm not sure, but have you installed dependencies?

**Comment by kylerlaird** [comment]
Where is package:secure_counter?

**Comment by furaiev** [comment]
@kylerlaird secure_counter is the name of the example app.

**Comment by kylerlaird** [comment]
Yes, I eventually figure that out, but it's a mystery in the example page.
https://pub.dev/packages/amazon_cognito_identity_dart_2/example
