### ISSUE TITLE
Wrong Username used when sending MFA when login using e-mail

### ISSUE THREAD

**Issue by pdyba** [furaiev/amazon-cognito-identity-dart-2#201]
Steps to reproduce:
1. Configure Cognito with login using e-mail.
2. Turn on MFA for the user outside the app. (I used totp)
3. Login using email and password
4. Input MFA code.
5. You should receive now
`InvalidParameterException Invalid device key given`
6. but despite that You can get a session and the application will still be working - just won't refresh the tokens becouse of lack of device key which is required by AWS Cognito.

Adding those lines  in /amazon_cognito_identity_dart_2-3.0.0/lib/src/cognito_user.dart line 598:
 ```
    if (username != srpUsername) {
      username = srpUsername;
    }
```
just after solves the issues
 ```
 String srpUsername = challengeParameters['USER_ID_FOR_SRP'];
```

![Screenshot 2022-06-30 at 16 45 08](https://user-images.githubusercontent.com/9288974/176710361-8fdf6448-0056-4f04-ab3f-0a8cebb45f24.png)

I can create PR with that but it might be a braking change so probably it should be introduced in diffrent way then the above. 
I can do it just needs some guidance ;)

ps. not this library specific If You ventured here somehow and You can switch to diffrent auth provider then cognito like auth0 do so ;) debuging cognito is very time consuming due to wrong error messages then You would expect and overall bad docs unless You are reading Amplify Code ;)

**Comment by AntonLT** [comment]
I spent 6 hours before I found the ticket and was able to resolve the same case described here.
Thank you, @pdyba for the solution
This should be included as a fix in the library, @furaiev
