### ISSUE TITLE
Persisting user session?

### ISSUE THREAD

**Issue by mailliwi** [furaiev/amazon-cognito-identity-dart-2#202]

**Comment by furaiev** [comment]
If you would like to use `cacheTokens()` you should implement and provide `CognitoStorage` interface.

Example - https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/main/example/lib/storage.dart

https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/main/lib/src/cognito_user_pool.dart#L34

**Comment by mailliwi** [comment]
I'm sorry, I have posted this issue by inadvertence. I have updated a clean issue. You may close this one
