### ISSUE TITLE
CognitoClientException 400 UnexpectedLambdaException

### ISSUE THREAD

**Issue by mikhael28** [furaiev/amazon-cognito-identity-dart-2#204]
Encountering an odd error every once in a while, a 400 request that seems to be related to socket timeouts. Anyone else seeing this?

The full error is below:

```
CognitoClientException{statusCode: 400, code: UnexpectedLambdaException, name: UnexpectedLambdaException, message: PostAuthentication invocation failed due to error Socket timeout while invoking Lambda function.}
```

**Comment by mikhael28** [comment]
Happens on login.

**Comment by CristopherVidalMachado** [comment]
You have a problem into your cognito integration lambda, for the trigger  PostAuthentication.

Verify your lambda fuction.

**Comment by mikhael28** [comment]
Thank you for your response! Closing.
