### ISSUE TITLE
Allow user to elect remembering the device with MFA

### ISSUE THREAD

**Issue by jazzdragon** [furaiev/amazon-cognito-identity-dart-2#206]
Looking at the code, looks like the package currently expects all the devices to be stored on cognito and would only require MFA on a new device. In a lot of situations this behavior needs to be opted-in by the user, so it would be helpful if that would be supported. Mentioned [here](https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/53#issuecomment-622587450).

**Comment by jazzdragon** [comment]
This will also resolve an issue where users can't sign in if the user pool has optional MFA and optional remembering devices set.

**Comment by furaiev** [comment]
@jazzdragon you are welcome to contribute to this feature if you have time and passion. 
Unfortunately, I'm overloaded and don't have time to contribute actively.

**Comment by inergarcia** [comment]
Greetings, does the remember device functionality already exist?
