### ISSUE TITLE
Unknown Error being thrown in case of SocketException

### ISSUE THREAD

**Issue by NischalJoshi777** [furaiev/amazon-cognito-identity-dart-2#207]
A change is added in version 2.1.0  where pattern matching is being used for handling socket exception.  To be specific the .toString() method being used in client.dart might have caused this issue.

**Comment by Gummiees** [comment]
Hey @NischalJoshi777, a bit late but this problem should have been fixed as of `3.4.0`, just in case you are still using the library and want to solve this issue :)
