### ISSUE TITLE
bug(fatal): CognitoUser.getSession throws TypeError when storage returns null for clockDrift

### ISSUE THREAD

**Issue by bjoernahrens** [furaiev/amazon-cognito-identity-dart-2#221]
This bug was introduced in 3.1.0 by commit 1a43b15e03f2953e1d563be36f887d65fa15de3a

[In `CognitoUser` line 195-196](https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/main/lib/src/cognito_user.dart#L195-L196)

```dart
195:    final clockDriftValue = await storage.getItem(clockDriftKey);
196:    final clockDrift = int.tryParse(clockDriftValue);
```	

`CognitoStorage.getItem` returns a `dynamic` type, which is really not optimal as then the Dart Analyzer ignores the fact that the value might be `null`.

In this case, the value returned in line 195 is `null` if no value was saved before.
However, `int.tryParse` has the following signature
```dart
  int? tryParse(String source, {int? radix});
```

The parameter `source` is a **non-optional** string. When given `null`, Dart will throw a `TypeError` **at runtime**.

`Error`s are usually not caught, so an app using this will crash.

**Comment by furaiev** [comment]
@bjoernahrens thank you for reporting,

@AndreiMisiukevich could you please take a look?

**Comment by AndreiMisiukevich** [comment]
@furaiev sure!

@bjoernahrens nice catch! I agree that it makes more sense to refactor code and replace dynamics with nullable Strings for easier maintenance.

**Comment by furaiev** [comment]
@bjoernahrens thanks for reporting, @AndreiMisiukevich thanks for fast fix!
