### ISSUE TITLE
Melos version bump?

### ISSUE THREAD

**Issue by mikhael28** [furaiev/amazon-cognito-identity-dart-2#235]
Hey @furaiev , love what you do here. I was wondering, are you using the `melos` monorepo package to organize your deployments? I'm getting this issue upgrading to 3.5 from 3.4, where another package that uses melos (3.0) and it seems is introducing some sort of incompatibility.

`[mobile] flutter pub get
Resolving dependencies...
Because no versions of flutter_zxing match >1.2.0 <2.0.0 and flutter_zxing 1.2.0 depends on melos ^3.0.0, flutter_zxing ^1.2.0 requires melos ^3.0.0.
And because melos >=0.5.0-dev.1 depends on http ^0.13.1 and amazon_cognito_identity_dart_2 >=3.5.0 depends on http ^1.0.0, flutter_zxing ^1.2.0 is incompatible with amazon_cognito_identity_dart_2 >=3.5.0.
So, because arms depends on both amazon_cognito_identity_dart_2 3.5.0 and flutter_zxing ^1.2.0, version solving failed.
exit code 1`

**Comment by mikhael28** [comment]
Would you mind making the http package support BOTH <1.0 and >= 1.0 package so that older packages that enforce 0.13.1 don't break when upgrading to the latest version of your package?

**Comment by furaiev** [comment]
@mikhael28 could you please test version `3.6.0-dev.1` ?

**Comment by mikhael28** [comment]
It works! Thank you for following up, I greatly appreciate it.
