### ISSUE TITLE
[ASK] Is it possible to getSession with only `refreshToken` value ?

### ISSUE THREAD

**Issue by derohimat** [furaiev/amazon-cognito-identity-dart-2#236]
In my case, I want to integrate a deeplink for login with refreshToken value.

For example
https://example.com/login?refreshToken=XYZ

And is it possible to send empty username into `CognitoUser` class ?

![image](https://github.com/furaiev/amazon-cognito-identity-dart-2/assets/3787041/0e2ec43e-7812-4995-b042-d99c56820053)
```
      final cognitoUser = CognitoUser('', Config.userPool);
      final cognitoRefreshToken = CognitoRefreshToken(refreshToken);
      final session = await cognitoUser.refreshSession(cognitoRefreshToken);
```

I have try but get this error.
![image](https://github.com/furaiev/amazon-cognito-identity-dart-2/assets/3787041/6b7b05e5-99bd-4e87-90a2-dd1110df4bf6)

**Comment by furaiev** [comment]
@derohimat I don't think AWS API allows it. At least JS lib doesn't allow - https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1386

**Comment by derohimat** [comment]
Solved, just put empty username and put refresh token here.

Example

```
          final cognitoUser = CognitoUser('', Config.userPool);
          final cognitoRefreshToken = CognitoRefreshToken(refreshToken);
          final newSession = await cognitoUser.refreshSession(cognitoRefreshToken);
```
