### ISSUE TITLE
Use case 19 

### ISSUE THREAD

**Issue by ryanlgoldmine** [furaiev/amazon-cognito-identity-dart-2#238]
Hi,

may I know any update with this? as the example is clearly not up to date. The implementation (https://pub.dev/packages/webview_flutter) I tried is not working. I have modified a bit and got an error claimed that is not the official browser, so I am not able to proceed to have Google Sign In.

**Comment by furaiev** [comment]
hello, probably this is an answer on your question - https://stackoverflow.com/a/59673634
