### ISSUE TITLE
CognitoUserDeviceConfirmationNecessaryException is not being thrown 

### ISSUE THREAD

**Issue by felipeapfer** [furaiev/amazon-cognito-identity-dart-2#239]
Hello @furaiev !
I`m running on this "issue" mentioned on #192 #165 . 
When User Opt-in is activated the ConfirmUser exception is thrown and I do believe it is due to the fact that this [PR](https://github.com/furaiev/amazon-cognito-identity-dart-2/pull/227) only throws CognitoUserDeviceConfirmationNecessaryException for MFA.

In this scenario I believe it would be correct to throw the CognitoUserDeviceConfirmationNecessaryException too since it is a valid option configuration of Cognito.

As a temporary work around one can check if there is a valid signInUserSession on the Exception object. If so it is an issue with the device registration otherwise it is indeed an error of user needs to confirm account.

**Comment by furaiev** [comment]
Hello @felipeapfer , thanks for reporting the issue. Could you please prepare a PR with the proposed fixes?
