### ISSUE TITLE
Enabling TOTP for MFA

### ISSUE THREAD

**Issue by ady-tsc** [furaiev/amazon-cognito-identity-dart-2#240]
Hi @furaiev  ,

I want to enable MFA by using TOTP. Currently, i'm using this enableMfa() function but it automatically enable SMS-MFA only for the MFA options. 

Is there any workaround to anable MFA using TOTP? 

thankyou!

**Comment by furaiev** [comment]
Hello @ady-tsc , I am not sure if it is available with the current implementation. Could you please check if it is available in the [official JS version](https://github.com/aws-amplify/amplify-js)?

**Comment by ady-tsc** [comment]
Hi @furaiev , i already saw the official docs that you mentioned before and also looked at the AWS documentation regarding [how to enable TOTP](https://docs.amplify.aws/lib/auth/mfa/q/platform/js/#setup-totp). There is no function that enabling the  TOTP method in amazon-cognito-identity-dart lib.
<img width="843" alt="Screenshot 2023-09-11 at 11 55 22" src="https://github.com/furaiev/amazon-cognito-identity-dart-2/assets/141003057/39f8ee7c-d062-4b85-b223-fb0ca97717ab">
The "enableMfa()" function also marked as deprecated for unknown reason.

But i looked at the aws-amplify lib and i notice that the implementation was defined there(same like the official docs from AWS). I want to ask for an opinion (because i'm new to AWS :_) ), 

1. Do those two repos have the same purpose and functionality? (aws-amplify and amazon-cognito-identity-dart)
2. Should i use two different lib in one app (amazon-cognito-identity-dart and aws-amplify) or should i migrate completely to aws-amplify if i want to use that TOTP method.

Thankyou!

**Comment by furaiev** [comment]
@ady-tsc I would recommend you to use official aws-amplify. I keep amazon-cognito-identity-dart alive just because aws-amplify doesn't have full set of features yet.

**Comment by furaiev** [comment]
closed with https://github.com/furaiev/amazon-cognito-identity-dart-2/pull/244
