### ISSUE TITLE
how to solve custom challenge?

### ISSUE THREAD

**Issue by mhernandezsuk** [furaiev/amazon-cognito-identity-dart-2#241]
My users' login requires the resolution of a CUSTOM_CHALLENGE and what happens is that initiateAuth() returns an exception, which says precisely that the user requires a CUSTOM_CHALLENGE to advance.

After this first step, the user completes the challenge data that arrives via email and enters a 6-digit code.

Now at this point when sending this challenge sendCustomChallengeAnswer() returns the following: CognitoClientException{statusCode: 400, code: InvalidParameterException, name: InvalidParameterException, message: Missing required parameter Session}

Session is not a parameter of the sendCustomChallengeAnswer() function and Session does not exist either since initAuth() returns an exception.

What alternative is there to this? Is it an implementation problem?

thank you !

**Comment by furaiev** [comment]
The session is included to request: https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/main/lib/src/cognito_user.dart#L811

Probably it is missed in your specific case

**Comment by Bptmn** [comment]
I got the same issue for SMS-MFA challenge.

No user session is retrieved.
I am well using sendMFACode function.

It seems that the storage does not work?

Any idea?

My signIn and confirmMfaCode functions:

```
Future<dynamic> signInUser(
  String email,
  String password,
) async {
  try {
    final userPool = CognitoUserPool(
      FFAppConstants.CognitoUserPoolId,
      FFAppConstants.CognitoClientId,
    );

    final user = CognitoUser(email, userPool);
    final authDetails =
        AuthenticationDetails(username: email, password: password);

    CognitoUserSession? session = await user.authenticateUser(authDetails);
    print(session);

    return {
      'status': 'SUCCESS',
      'message': 'User signed in successfully.',
    };
  } on CognitoUserMfaRequiredException catch (e) {
    print('Challenge parameters: ${e.challengeParameters}');
    print(e.challengeName);
    print(e.challengeParameters);
    print(e.message);

    // Extract the session directly from the exception
    final session = e.challengeParameters['Session'];
    print('Captured session: $session');

    return {
      'status': 'MFA_REQUIRED',
      'message': 'MFA is required. Use confirmMfaCode to proceed.',
      'session': session, // Include session in response
    };
  } catch (e) {
    print(e);
    return {
      'status': 'ERROR',
      'message': e.toString(),
    };
  }
}
```


```
Future<dynamic> confirmMfaCode(
  String email,
  String mfaCode,
) async {
  try {
    // Initialize CognitoUserPool
    final userPool = CognitoUserPool(
      FFAppConstants.CognitoUserPoolId,
      FFAppConstants.CognitoClientId,
    );

    // Create CognitoUser
    final user = CognitoUser(email, userPool);

    // Call the sendMFACode method and print the response
    CognitoUserSession? userSession = await user.sendMFACode(mfaCode);

    return {
      'status': 'SUCCESS',
      'message': 'MFA verified successfully. User authenticated.',
    };
  } catch (e) {
    print('[confirmMfaCode] Error during MFA Verification: $e');
    return {
      'status': 'ERROR',
      'message': e.toString(),
    };
  }
}
```
