### ISSUE TITLE
VerifyDevice request fails if username used in sendMFA() is email or phone number

### ISSUE THREAD

**Issue by AntonLT** [furaiev/amazon-cognito-identity-dart-2#247]
Thank you, @pdyba for the solution
This should be included as a fix in the library

_Originally posted by @AntonLT in https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/201#issuecomment-1867571486_

**Comment by furaiev** [comment]
Hello @AntonLT @pdyba,
please create a PR
