### ISSUE TITLE
MFA_SETUP challenge when user pool has "required MFA"

### ISSUE THREAD

**Issue by Kulodo** [furaiev/amazon-cognito-identity-dart-2#248]
In the Amazon Cognito userPool setup there is the option to have "required MFA"  or "optional MFA".
When I select "required MFA" and then run my app I get the MFA_SETUP challenge ( see below ).
  
I think I'm then meant to call associateSoftwareToken() but at that point the session is null and the 'User is not authenticated' exception is thrown in CognitoUser._signInUserSessionCheck.   Am I doing something wrong?

The amazon hosted UI is working fine with "required MFA".

When I select "optional MFA" and then run the app then CognitoUserSession is returned correctly.   I presume I could then call associateSoftwareToken() and verifySoftwareToken() as I'll have a valid session, and then setUserMfaPreference.
 
```
    CognitoUserSession? session;
    try {
      session = await cognitoUser.authenticateUser(authDetails);
    } on CognitoUserMfaSetupException catch (e) {
      // handle MFA_SETUP challenge
      final code = await cognitoUser.associateSoftwareToken();


    } catch (e) {
    }

```

**Comment by miavorac** [comment]
I encountered same issue. The session is null so there's nothing I can do with proceeding and verifying the TOTP code for the user
