### ISSUE TITLE
Tell us about this package

### ISSUE THREAD

**Issue by leecommamichael** [furaiev/amazon-cognito-identity-dart-2#25]
I notice this takes another package and adds a '2' to the end of its' name and is a fork of that package. I assume that you needed the original package and that it was no longer supported by the original developer, so you started building on top of it?

I ask because I need this package but it looks strange and I want something that will be supported (not asking for new features).

**Comment by furaiev** [comment]
@leecommamichael you are correct.
Original package is abandoned by author, this one is supported by community.
