### ISSUE TITLE
"Missing required parameter Session" while  MFA is required

### ISSUE THREAD

**Issue by dhara-seaflux** [furaiev/amazon-cognito-identity-dart-2#253]
When attempting to authenticate the user in my app, I encountered a CognitoUserMfaRequiredException, indicating that MFA is required for my user pool. Upon receiving this exception, I attempted to send the OTP using the sendMFACode function, but encountered the following error:

flutter: CognitoUserException: "SMS_MFA"
flutter: MFA is required: CognitoUserException: "SMS_MFA"
flutter: CognitoClientException{statusCode: 400, code: InvalidParameterException, name: InvalidParameterException, message: Missing required parameter Session}

**Comment by miavorac** [comment]
I have the same problem. Upon sending valid credentials, the session is always null so any attempt for TOTP or SMS_MFA fails.

**Comment by furaiev** [comment]
please check if you have session here: https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/main/lib/src/cognito_user.dart#L931

**Comment by BennyM88** [comment]
Have you been able to fix it somehow? @dhara-seaflux @miavorac

**Comment by miavorac** [comment]
Hi, sorry for late reply but yes. It works now! 

I didn't know that I need to call sendMFACode for 2FA auth. 
So all good now. 

Thank you 🙏

**Comment by Bptmn** [comment]
I got the same issue.

The user session is always empty when I check it in both functions below.
I am well using sendMFACode function.

Any idea?

My signIn and confirmMfaCode functions:
`Future<dynamic> signInUser(
  String email,
  String password,
) async {
  try {
    final userPool = CognitoUserPool(
      FFAppConstants.CognitoUserPoolId,
      FFAppConstants.CognitoClientId,
    );

    final user = CognitoUser(email, userPool);
    final authDetails =
        AuthenticationDetails(username: email, password: password);

    CognitoUserSession? session = await user.authenticateUser(authDetails);
    print(session);

    return {
      'status': 'SUCCESS',
      'message': 'User signed in successfully.',
    };
  } on CognitoUserMfaRequiredException catch (e) {
    print('Challenge parameters: ${e.challengeParameters}');
    print(e.challengeName);
    print(e.challengeParameters);
    print(e.message);

    // Extract the session directly from the exception
    final session = e.challengeParameters['Session'];
    print('Captured session: $session');

    return {
      'status': 'MFA_REQUIRED',
      'message': 'MFA is required. Use confirmMfaCode to proceed.',
      'session': session, // Include session in response
    };
  } catch (e) {
    print(e);
    return {
      'status': 'ERROR',
      'message': e.toString(),
    };
  }
}`

`Future<dynamic> confirmMfaCode(
  String email,
  String mfaCode,
) async {
  try {
    // Initialize CognitoUserPool
    final userPool = CognitoUserPool(
      FFAppConstants.CognitoUserPoolId,
      FFAppConstants.CognitoClientId,
    );

    // Create CognitoUser
    final user = CognitoUser(email, userPool);

    // Call the sendMFACode method and print the response
    CognitoUserSession? userSession = await user.sendMFACode(mfaCode);

    return {
      'status': 'SUCCESS',
      'message': 'MFA verified successfully. User authenticated.',
    };
  } catch (e) {
    print('[confirmMfaCode] Error during MFA Verification: $e');
    return {
      'status': 'ERROR',
      'message': e.toString(),
    };
  }
}`
