### ISSUE TITLE
Mismatched key prefix when caching and restoring device

### ISSUE THREAD

**Issue by benja8151** [furaiev/amazon-cognito-identity-dart-2#255]
I've noticed that whenever I login (with `authenticateUser`) a new device is registered in Cognito. I found out that `keyPrefix` used in `cacheDeviceKeyAndPassword` and `getCachedDeviceKeyAndPassword` functions is not the same. This means that `getCachedDeviceKeyAndPassword` function **never** successfully restores cached device.

For illustration, I printed out `keyPrefix` used in both functions:
```shell
getCachedDeviceKeyAndPassword KEY PREFIX: CognitoIdentityServiceProvider.<clientID>.test.user@email.com

cacheDeviceKeyAndPassword KEY PREFIX: CognitoIdentityServiceProvider.<clientID>.404fa7dd-29f4-462f-b746-8e453f8fe3a8
```

 The end of key prefix is email address in `getCachedDeviceKeyAndPassword` and Cognito username in `getCachedDeviceKeyAndPassword`. 

I'm using email as username when creating `CognitoUser` on login, like so: 
```dart
CognitoUser user = CognitoUser(email, _cognitoUserPool!)
``` 
Could this be a problem, since `keyPrefix` is constructed from username, and I'm guessing username is set to email address when first calling `getCachedDeviceKeyAndPassword` :
```dart
  String get keyPrefix => 'CognitoIdentityServiceProvider.${pool.getClientId()}.$username';
```

**Comment by benja8151** [comment]
I think https://github.com/furaiev/amazon-cognito-identity-dart-2/commit/08e43d6686931d2890816cc3a86e83910e8b1c4a might be linked to this, because it seems email in `username` field in `CognitoUser` is replaced by user id in this step.

**Comment by furaiev** [comment]
@benja8151 
you are correct, in the [original package](https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js) the `keyPrefix` consist username or not from time to time.
We need to copy this logic, which should fix the issue.
Can you please update your PR based on `amplify-js`?

**Comment by anthonycastelli** [comment]
Has there been an update on this? I'm now running into a similar issue
