### ISSUE TITLE
Flutter Channel Dev 1.15 issue

### ISSUE THREAD

**Issue by furaiev** [furaiev/amazon-cognito-identity-dart-2#26]
I follow the example app, and implement it to my app.
Once publish it, got an issue after create a release version.
After the user session is over (1 hour after), user no longer able to access the app.
the _getValues was throwing error :
"error type '_onebytestring' is not a subtype of type 'int' of 'index'"

I though there's something wrong with my code.
But when I try release the example, the same thing happen. 
Secure Counter page & Login page always show "Loading..."

When check it, the actual error came from _cognitoUser.getSession() method.

I honestly don't know what happen here (I'm new to Flutter)
It seem, this issue not happen on debug mode, only when release.

_Originally posted by @erw13n in https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/24#issuecomment-588240795_

**Comment by nezz0746** [comment]
Hi i'm having the same issue when trying to release an apk, everything works fine in debug. My error seems to be triggered by **getAwsCredentials** from CognitoCredentials:

>  "type '_OneByteString' is not a subtype of type 'int' of 'index'"

I come from react-native so i'm new to this as well but it'd be great to have some help on this.

**Comment by erw13n** [comment]
Make sure you run Flutter Stable Channel and not Dev Channel.
https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/24#issuecomment-590617242

**Comment by nezz0746** [comment]
@erw13n Ah yes thanks that was the issue, i was actually on Dev this whole time... Thanks !
