### ISSUE TITLE
User not autenticated

### ISSUE THREAD

**Issue by riyaz2011** [furaiev/amazon-cognito-identity-dart-2#262]
(MFA is required) Hey I'm getting error 'user is not authenticated' when hitting the associateSoftwareToken.Please help on this.

**Comment by furaiev** [comment]
hello @riyaz2011,
we had [a similar issue](https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/248) but we don't have a hero who can fix the issue and create a PR. 😞

**Comment by kwameopareasiedu** [comment]
@furaiev @riyaz2011 Just submitted a PR which addresses this...

**Comment by furaiev** [comment]
please check version 3.7.0
