### ISSUE TITLE
Insecure Encryption Mechanisms 

### ISSUE THREAD

**Issue by prashant-ERA** [furaiev/amazon-cognito-identity-dart-2#264]
I am using amazon_cognito_identity_dart_2 package in my project. The version I am using is 3.6.5. During code review it has been highlighted that cryptographically weak encryption algorithms like "RSA/ECB/PKCS1Padding" are being used in the package. Please advice if you plan to update these weak encryption algorithms to accepted encryption algorithms in the updated version of the package.

![A](https://github.com/user-attachments/assets/fb8384e0-66d9-4c2b-b5e2-6ef90b9a42b7)

**Comment by furaiev** [comment]
hello @prashant-ERA,
Could you please point to the place where it is used? It looks like these algorithms are used by your storage not by the package.
