### ISSUE TITLE
Federated identity provider support?

### ISSUE THREAD

**Issue by kbokarius** [furaiev/amazon-cognito-identity-dart-2#33]
I looked through the documentation and it's not clear whether this library has support for signing in via Google, Facebook, etc on mobile devices. I assume that there must be a way to pop up a browser, display the third party sign on page, and then redirect back to the app, but is that something that this library can facilitate or support?

**Comment by furaiev** [comment]
There should be the same flow as in [amplify js](https://aws-amplify.github.io/docs/js/authentication#social-providers-and-federation)

**Comment by kbokarius** [comment]
@furaiev sorry, I dug into the documentation, but it's not clear to me how the AWS JS components can be applied to a Flutter app? In my case the app is only for iOS and Android, not for web. I see there are Flutter sign-in packages like google_sign_in, can amazon-cognito-identity-dart-2 be used with them in some way? I'm just not clear on whether amazon-cognito-identity-dart-2 can be used with federated sign in so that I can still keep track of users and sessions in amazon-cognito-identity-dart-2 (but have them sign in through Google or Facebook).

**Comment by kbokarius** [comment]
It looks like the hosted UI can be used to go directly to the Google sign in page:

`https://<YOUR_DOMAIN>.auth.<REGION>.amazoncognito.com/oauth2/authorize?identity_provider=Google&redirect_uri=<REDIRECT_URI>&response_type=TOKEN&client_id=<CLIENT_ID>&scope=openid`

And I'm not certain yet, but it appears that the page redirects to the redirect URI and passes a code which I assume is the Authorization Code. Maybe I can then use that code in conjunction with `amazon-cognito-identity-dart-2`?  I have no idea if I'm taking the right steps or if there is an easier way to do this.

**Comment by kbokarius** [comment]
I'm still struggling with this. I'm able to get an authorization code (in the form of a GUID) after Google redirects to the redirect URI, but I can't figure out a way to use this library to use that code to get the refresh and access tokens.

**Comment by kbokarius** [comment]
Progress: I had to make a POST request to: https://<YOUR_DOMAIN>.amazoncognito.com/oauth2/token?grant_type=authorization_code&client_id=<CLIENT_ID>&code=<AUTH_CODE>&redirect_uri=myapp://

Using the code I got back from the authorize request, and now I have my tokens. I guess now I'll try to manually create a CognitoUser/session with the tokens.

**Comment by kbokarius** [comment]
Ok, I have it working, but because CognitoUser._signInUserSession is private, I had to create a custom CognitoUser class in my code to set the session. Not ideal, it would be great to add _signInUserSession to the CognitoUser constructor. But now it looks like I can use federated Cognito sign in via a web view, get the auth grant code, make a POST request as explained above, and then use my custom CognitoUser class to manage the session. I'm still testing but so far it seems to work as expected.

**Comment by furaiev** [comment]
Hi @kbokarius , thank you for your work.
You are welcome to create PR with proposed changes.

**Comment by kbokarius** [comment]
@furaiev https://github.com/furaiev/amazon-cognito-identity-dart-2/pull/34

**Comment by robert-stevens** [comment]
@kbokarius 

Thanks for the use case 19 example, I get an error on this line:

`final user = CognitoUser(email, userPool, signInUserSession: session);`

email is not defined.

Where/how do you get email?

**Comment by kbokarius** [comment]
@robert-stevens sorry, email should just be set to null in that line of code. You need to first get the attributes and then set the email (make sure you have email attribute selected in Cognito and mapped to the email field in the identity provider), but you can pass it as null in the constructor. It's kind of a roundabout way to do it but it gets the job done without more impactful changes to this lib. I'll create a PR to update the readme now.

**Comment by robert-stevens** [comment]
Thanks, I will check it out.

**Comment by kbokarius** [comment]
https://github.com/furaiev/amazon-cognito-identity-dart-2/pull/38
