### ISSUE TITLE
Question: Is it possible to upload video with this plugin?

### ISSUE THREAD

**Issue by Subfly** [furaiev/amazon-cognito-identity-dart-2#36]
As the title suggest, I need to develop an app with huge userbase but we need to use AWS. Is it possible to upload and get videos with this package?

**Comment by furaiev** [comment]
@Subfly here is an example of images loading https://github.com/conghua2411/FlutterDemoEverything/blob/e07cd5e1c9f751395a050a9a37ed09e821ee607b/lib/aws_cognito_dev_upload_s3/aws_cognito_dev_upload_s3.dart

I believe you can load videos in the same way.

**Comment by furaiev** [comment]
@Subfly have you managed to upload a video?
