### ISSUE TITLE
getUserAttributes Type Error

### ISSUE THREAD

**Issue by solokia** [furaiev/amazon-cognito-identity-dart-2#39]
both

> final attributes = await _cognitoUser.getUserAttributes();
> List<CognitoUserAttribute> attributes = await _cognitoUser.getUserAttributes();

getting this error:
_TypeError (type 'List<dynamic>' is not a subtype of type 'FutureOr<List<CognitoUserAttribute>>')

Kind of new to fluttter and all but strict type casting seems to be giving quite a bit of error recently.

Changing 
> Future<List<CognitoUserAttribute>> getUserAttributes() async {  

to
> Future getUserAttributes() async {  

does work but I'm not really sure if it should be done this way.

**Comment by nashfive** [comment]
@furaiev I've just got the same error and opened a PR to fix it.

**Comment by furaiev** [comment]
@nashfive thank you for the fix, it's available as of version 0.1.12+2
