### ISSUE TITLE
Token is not from a supported provider of this identity pool

### ISSUE THREAD

**Issue by subhendukundu** [furaiev/amazon-cognito-identity-dart-2#42]
Trying to add facebook login with AWS Cognito. After loggin using https://pub.dev/packages/flutter_facebook_login I am trying to pass the details to AWS. But its throwing error of
Exception has occurred. CognitoClientException (CognitoClientException{statusCode: 400, code: NotAuthorizedException, name: NotAuthorizedException, message: Token is not from a supported provider of this identity pool.})
What am I doing wrong?
```
  _loginWithFB() async{
    final result = await facebookLogin.logIn(['email']);

    switch (result.status) {
      case FacebookLoginStatus.loggedIn:
        final token = result.accessToken.token;
        final graphResponse = await http.get('https://graph.facebook.com/v2.12/me?fields=name,picture,email&access_token=${token}');
        final profile = JSON.jsonDecode(graphResponse.body);
        print(profile);
        final _userPool = new CognitoUserPool('ap-south-1_XXXXXXXXX', 'xxxxxxxxxxxxxxxxxxxxx');
        final _credential = new CognitoCredentials('ap-south-1:xxxxxxxxx-xxxx-xxxx-xxxxxxxxxxx', _userPool);
        await _credential.getAwsCredentials(token, 'graph.facebook.com');
        print(_credential.sessionToken);
        setState(() {
          userProfile = profile;
          _isLoggedIn = true;
        });
        break;

      case FacebookLoginStatus.cancelledByUser:
        setState(() => _isLoggedIn = false );
        break;
      case FacebookLoginStatus.error:
        setState(() => _isLoggedIn = false );
        break;
    }

  }
```
Thanks in advance.

**Comment by subhendukundu** [comment]
I have no progress on this. Any help?
I tried with a different amplify account too. I am facing the issue.
```
android facebook:
Unhandled Exception: CognitoClientException{statusCode: 400, code: NotAuthorizedException, name: NotAuthorizedException, message: Token is not from a supported provider of this identity pool.}
ios facebook:
Exception: CognitoClientException{statusCode: 400, code: NotAuthorizedException, name: NotAuthorizedException, message: Token is not from a supported provider of this identity pool.}

android google:
name: NotAuthorizedException, message: Invalid login token. Not a valid OpenId Connect identity token.}
ios google:
code: NotAuthorizedException, name: NotAuthorizedException, message: Invalid login token. Not a valid OpenId Connect identity token.
```
I am able to fetch the user data, but not able to add it in the Cognito. Did I set up the Cognito wrong?

**Comment by chandong83** [comment]
hello,
I had the same problem.
In my case it was caused by not adding Facebook ID to "Manage Identity Pools" settings.
Please refer to the link below.
https://docs.aws.amazon.com/cognito/latest/developerguide/facebook.html


![1](https://user-images.githubusercontent.com/4668984/78103348-b48e6980-7427-11ea-897f-09b64b49161a.png)
![2](https://user-images.githubusercontent.com/4668984/78103351-b5bf9680-7427-11ea-8f73-0de078662049.png)

**Comment by subhendukundu** [comment]
Yes yes, that was it. Dang, I missed that it doesn't support user pool, it supports only the identity pool for social login. So Facebook login is working.
Now issue with Google login. Reading through [aws-openid] (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html) I understand if we are using multi clientID we can user OpenID to solve the issue. So I added the open id in IAM with help of [this](https://medium.com/fullstack-with-react-native-aws-serverless-and/create-aws-identity-pool-f807d008d26f#ae1e). But it still throwing `Invalid login token. Not a valid OpenId Connect identity token.`
I have added the following code
```
final GoogleSignInAccount googleSignInAccount = await _googleSignIn.signIn();
final GoogleSignInAuthentication googleSignInAuthentication = await googleSignInAccount.authentication;
setState(() {
_isLoggedIn = true;
});
print(googleSignInAuthentication);
final _credential = new CognitoCredentials(_identityPoolId, _userPool);
await _credential.getAwsCredentials(googleSignInAuthentication.accessToken, 'accounts.google.com');
print('aws google login done');
print(_credential.sessionToken);
```
Is it not the `googleSignInAuthentication.accessToken`?
If I look at first image i see facebook as connected method, is it normal as openid is not showing as openid. What am I missing now?
<img width="1080" alt="Screenshot 2020-04-01 at 9 16 42 PM" src="https://user-images.githubusercontent.com/20059141/78159212-e3283680-745f-11ea-9e08-53b9c8c83901.png">
<img width="1076" alt="Screenshot 2020-04-01 at 9 18 02 PM" src="https://user-images.githubusercontent.com/20059141/78159216-e58a9080-745f-11ea-8860-a93f2bceaa37.png">

**Comment by subhendukundu** [comment]
Update: I have changed `await _credential.getAwsCredentials(googleSignInAuthentication.accessToken, 'accounts.google.com');` to `await _credential.getAwsCredentials(googleSignInAuthentication.idToken, 'accounts.google.com');`
This is wokring on iOS but not with android.
As  the idToken is null on android. Checking how to fix that. 
```
GoogleSignInAuthentication:{accessToken: ya29.a0#####################OPMReiWUcSjIUJ50y1EclMQcdIbBEzKE10Fm1vCAeHWr36AgDuuGmOkMRbc_Zd2DJ-gZlzpSYvuj, idToken: null}
```

**Comment by devDeejay** [comment]
Google login not working for Android is giving the error:

**Unhandled Exception: CognitoClientException{statusCode: 400, code: NotAuthorizedException, name: NotAuthorizedException, message: Token is not from a supported provider of this identity pool.**

I configured both of the following after registering the Google SignIn for android app from https://developers.google.com/identity/sign-in/web/sign-in

- Federation Identity Providers in Cognito Pool and
- Federated Identities in Identity Pool 

Tried multiple times but still no luck. So please help.

**Comment by furaiev** [comment]
If you have ideas on how to improve this part - welcome to contribute.
