### ISSUE TITLE
Exception in production APK | not in DEBUG APK | Unhandled Exception: type '_OneByteString' is not a subtype of type 

### ISSUE THREAD

**Issue by masbaehr** [furaiev/amazon-cognito-identity-dart-2#43]
I'm getting this exception on production apk in Pixel3A Android10

```txt

2020-03-30 10:03:58.923 2263-2289/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type '_OneByteString' is not a subtype of type 'int' of 'index'
    #0      CognitoIdentityId.getIdentityId (package:amazon_cognito_identity_dart_2/src/cognito_identity_id.dart:51)
    <asynchronous suspension>
    #1      CognitoCredentials._getAwsCredentials (package:amazon_cognito_identity_dart_2/src/cognito_credentials.dart:52)
    <asynchronous suspension>
    #2      CognitoCredentials.getAwsCredentials (package:amazon_cognito_identity_dart_2/src/cognito_credentials.dart:38)
    <asynchronous suspension>

```

**Comment by dkobia** [comment]
Running into this issue as well with production APK on Android. It occurs on `getAwsCredentials`

**Comment by furaiev** [comment]
@masbaehr  @dkobia  Thanks for reporting. Could you please investigate the reason of the error? Ideally with a proposed fix.

As a quick check please try to downgrade to 0.1.9.

**Comment by masbaehr** [comment]
Debugging is not that easy as it happens only in production but i can say that the error is caused by this line:

FILE:
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/master/lib/src/cognito_identity_id.dart

LINE:
this.identityId = data['IdentityId'];

Possibly related to some difference in Type safety in Debug vs. Release? 

Actually i'm not even sure the real "root cause" is this library. It could very well be a bug in the flutter sdk itself.

**Comment by dkobia** [comment]
@furaiev -- the issue is probably because I'm in the `dev` channel instead of `stable` on flutter as referenced in this ticket: https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/24#issuecomment-590617242

Unfortunately I can't switch back to stable because I'm relying on fixes made in the `dev` channel, so that leaves me unfortunately having to explore other options.

**Comment by dkobia** [comment]
It looks like this issue has been resolved in `v1.16.4-pre.83` (dev channel).

**Comment by masbaehr** [comment]
Also not happening anymore with Flutter v.1.18.1-pre.15 , so i guess this can be closed

**Comment by batara666** [comment]
are you sure
