### ISSUE TITLE
getSession is called on nul

### ISSUE THREAD

**Issue by kebsont** [furaiev/amazon-cognito-identity-dart-2#45]
Hello,
When I try to get the currentUser() from Page to Page I got this error.

> flutter: The error;
> flutter: NoSuchMethodError: The method 'getSession' was called on null.
> 
> Receiver: null

Here my code
```dart
Future<UserService> _getValues() async {
    try {
      final user = await userPoolSettings.getCurrentUser();
      final session = await user.getSession();
      print(session);
    } catch (e) {
      print("The error; ");
      print(e);
    }
    return _userService;
  }
```

My userPool definition is like this, with great credentials
```dart
  static final userPoolSettings = new CognitoUserPool(
     xxxxxxxxx, xxxxxx);
```

**Comment by furaiev** [comment]
@kebsont sorry for the long reply,
Have you managed to fix the issue?

**Comment by kebsont** [comment]
Hello @furaiev , no
I finally changed and used another technologie.

**Comment by furaiev** [comment]
Ok, then I close this issue.
