### ISSUE TITLE
For S3 GET Object possible with accesskeyid and secret?

### ISSUE THREAD

**Issue by crazedVic** [furaiev/amazon-cognito-identity-dart-2#47]
Your example shows using cognito.  is it difficult to change this to use accesskeyid and secret? I managed to get S3 upload working (code below) but for GET's (and DELETE's) which don't have request body's but instead rely on header values, i have had no luck.

```
Future<Map> send(
      {@required String imagePathOfPhone,
      @required String imagePathInS3Bucket,
      @required String bucketName,
      @required String accessKeyId,
      @required String secretKeyId,
      @required String region,
      @required String s3Endpoint}) async {
    final file = File(imagePathOfPhone);
    final stream = http.ByteStream(DelegatingStream.typed(file.openRead()));
    final length = await file.length();

    final uri = Uri.parse(s3Endpoint);
    final req = http.MultipartRequest("POST", uri);
    final multipartFile = http.MultipartFile('file', stream, length,
        filename: path.basename(file.path));

    final policy = Policy.fromS3PreSignedPost(
        imagePathInS3Bucket, bucketName, accessKeyId, 15, length,
        region: region);
    final key =
        SigV4.calculateSigningKey(secretKeyId, policy.datetime, region, 's3');
    final signature = SigV4.calculateSignature(key, policy.encode());

    req.files.add(multipartFile);
    req.fields['key'] = policy.key;
    req.fields['acl'] = 'public-read';
    req.fields['X-Amz-Credential'] = policy.credential;
    req.fields['X-Amz-Algorithm'] = 'AWS4-HMAC-SHA256';
    req.fields['X-Amz-Date'] = policy.datetime;
    req.fields['Policy'] = policy.encode();
    req.fields['X-Amz-Signature'] = signature;

    try {
      final res = await req.send();
 [...]
```
Any chance you can point me in the right direction?

x-amz-security-token:${_credentials.sessionToken}
_credentials.secretAccessKey
 are the two fields i can't figure out doing the non-cognito way.

Any help is much appreciated.

**Comment by s4-ali** [comment]
Hi, can you share code how you managed to upload file to the database, some complete example would be really really helpful as I am stuck here for a month. Thanks in advance :)

**Comment by crazedVic** [comment]
You are trying to use flutter to upload and delete images on S3?

**Comment by s4-ali** [comment]
> You are trying to use flutter to upload and delete images on S3?
Yes just managed to upload file to AWS s3 using your code so thanks :) but you are using post method here and I was getting an invalid method in response so I changed "post" to "put" and not it is working fine.

**Comment by crazedVic** [comment]
i actually found a much simpler way to get this working, eventually.
Using these packages:
`import 'package:amazon_s3_cognito/amazon_s3_cognito.dart';
import 'package:amazon_s3_cognito/aws_region.dart';`

this code works really well, as long as you use US_EAST, since for some reason the author of this plugin decided to hard-code region into his android code.  So the Identity Pool id also works best if you set it up US_EAST region.  The original author also decided to use subregions and not make them optional, but you can just use US_EAST_1 twice, as seen below.

```
 Future chooseFile() async {
    await ImagePicker.pickImage(source: ImageSource.gallery).then((image) {
      setState(() {
        _image = image;
        _uploadToS3();
      });
    });
  }
  void _uploadToS3() async{
    // refer to bottom of https://stackoverflow.com/questions/53811487/upload-fetch-media-files-from-aws-s3-in-flutter/57636615#57636615
    // only seems to work with US_EAST_1 S3 Buckets (android plugin is hardcoded to east)

    //syntax to upload
    String uploadedImageUrl = await AmazonS3Cognito.upload(
        _image.path,
        "execrentals-east",
        "us-east-1:xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "properties/id_01/image_1.png",
        AwsRegion.US_EAST_1,
        AwsRegion.US_EAST_1);
}

void _deleteFromS3() async{
     //syntax to delete
    String result = await AmazonS3Cognito.delete(
        "execrentals-east",
        "us-east-1:xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "properties/id_01/image_1.png",
        AwsRegion.US_EAST_1,
        AwsRegion.US_EAST_1);
}
```

**Comment by s4-ali** [comment]
Okay thank you will definitely try this.
