### ISSUE TITLE
The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by Rayv1** [furaiev/amazon-cognito-identity-dart-2#5]
Hi,

i try to query a API GW with your plugin, but when i insert an umlaut like 'ä,ö,ü' its not working correctly and ive got the error:
"{message: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

Without Umalute its working quite well.

Request i sent

### Canonical Request sent
GET
/path/%C3%A4

accept:application/json
content-type:application/json
host:yyyyyyy.execute-api.eu-central-1.amazonaws.com
x-amz-date:20191229T163450Z

**Exception:**

{message: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

### The Canonical String for this request should have been
'GET
/path/%25C3%25A4

accept:application/json
content-type:application/json
host:yyyyyyy.execute-api.eu-central-1.amazonaws.com
x-amz-date:20191229T163450Z
}

**Comment by Rayv1** [comment]
I dont know exactly where, but i think there is an issue with url encoding.

**Comment by furaiev** [comment]
Hi @Rayv1,
I think `ä` is `%C3%A4` or this is a Dart bug, pls take a look:
https://dartpad.dev/2922d18b2a856889408a379246c0759a

**Comment by Rayv1** [comment]
hi @furaiev 

yes ä is %C3%A4 but aws gateway wants a path with %25C3%25A4, which is an utf-8 encoded %C3%A4,  which in turn is an ä.

However, it is happening with every Special Character. Even with '&' or '!' its not working.

For me it seems like the path in the CanonicalRequestof the SigV4Request shouldnt be utf-8 decoded, because the api gw is already doing it.

**Comment by furaiev** [comment]
It's interesting, I'll check.
Thank you!

**Comment by Rayv1** [comment]
@furaiev 

iam not sure but...

another cause may be that the http instance is also doing an utf8-encoding.

the url iself is never encoded with utf8 by this plugin. But the CanonicalUri is by the following function:

 static String buildCanonicalUri(String uri) {
    return Uri.encodeFull(uri);
  }

this could be the Problem for the double Encoding, while the Url is only one time encoded by the http instance.

**Comment by furaiev** [comment]
Closed.
Pls write if needed to reopen.
