### ISSUE TITLE
getAWSCredentials with Google

### ISSUE THREAD

**Issue by Kacpur** [furaiev/amazon-cognito-identity-dart-2#50]
Hi,

how can I authenticate user with Google using getAWSCredentials method? In the documentation there is en example for Facebook, saying that I need to pass 'graph.facebook.com' as a second parameter. I'm new to social auth and I do not know what is equivalent for that for Google or where actually search for it.

Just to add, I do not manage AWS Pools, I only do mobile app using whatever I am provided from AWS team.

**Comment by furaiev** [comment]
Hi, maybe @dagovalsusa can help you, but I'm not sure...

**Comment by dagovalsusa** [comment]
I hope this guide can help you

https://docs.aws.amazon.com/cognito/latest/developerguide/google.html

**Comment by Kacpur** [comment]
@dagovalsusa Thank you, I will check it as soon as I will be able.
