### ISSUE TITLE
Check MFA status

### ISSUE THREAD

**Issue by lain-ke** [furaiev/amazon-cognito-identity-dart-2#52]
Is there any way to see if the user has multiple factor authentication activated or not?

**Comment by furaiev** [comment]
Yes, it returns a `challengeName`, search `challenge` in this repo.

**Comment by lain-ke** [comment]
I mean check it once the user is already logged in.
In my case, I am making a settings screen, where there is an option to activate 2MFA, so that's why I need to check it.

**Comment by furaiev** [comment]
So, in the login process, you already know if the user enters the MFA codes or not.
Based on this data you can determine if 2MFA is activated, correct?

**Comment by lain-ke** [comment]
Normally yes, but what if the user is logged in in multiple devices, and in one of them disables/enables 2MFA? That would not update on all devices.

**Comment by furaiev** [comment]
I think you should keep this value in your DB then.

**Comment by lain-ke** [comment]
That's a bad practice.

**Comment by furaiev** [comment]
@lain-ke 
please add this code into your `flutter/.pub-cache-hosted/pub.dartlang.org/amazon-cognito-identity-dart-2-0.1.9/lib/src/cognito_user.dart` and build the app.
Try to call this method. If it works I'll publish a new version.
In my case I don't have the key `MFAOptions` in the response, but I suppose this is adjustable in the AWS admin panel.

```
/// This is used by an authenticated user to get the MFAOptions
  Future<List> getMFAOptions(callback) async {
    if (!(_signInUserSession != null && _signInUserSession.isValid())) {
      throw Exception('User is not authenticated');
    }

    final paramsReq = {
      'AccessToken': _signInUserSession.getAccessToken().getJwtToken(),
    };
    final userData = await client.request('GetUser', paramsReq);
    print(userData);
    return userData['MFAOptions'];
  }
```

**Comment by lain-ke** [comment]
Hello, I also don't have the MFAOptions key parameter, is there any way to enable it?

**Comment by furaiev** [comment]
Yeap, in this case, it works:
```
await cognitoManager.cognitoUser.enableMfa();
var mfaOptions = await cognitoManager.cognitoUser.getMFAOptions();
print(mfaOptions);
```

**Comment by furaiev** [comment]
@lain-ke do you have any feedback? Is this code is useful?

**Comment by furaiev** [comment]
@ShogoTsuchiya `cognitoManager` is a custom class that keeps CognitoUserPool and CognitoUser.
You can create and use directly CognitoUser.

**Comment by ShogoTsuchiya** [comment]
Thank you for your reply. I tried to direct use like this.
    await cognitoUser.getMFAOptions();
but it always returns NULL...

**Comment by furaiev** [comment]
it means that server returns `userData` without `MFAOptions`
https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/7378a4e2afff03df98616b4298f1c1a2cb468a66/lib/src/cognito_user.dart#L986

**Comment by ShogoTsuchiya** [comment]
Thanks!
You mean I can get MFAOptions info as a part of attributes, like 'sub' and 'email_verified' ?

**Comment by jazzdragon** [comment]
Looks like the MFA options are in `userData['UserMFASettingList']`, so the current implementation of `cognitoUser.getMFAOptions()` will always return null.
