### ISSUE TITLE
Google Authentication : Couldn't Sign you in - The browser or app may not be secure.

### ISSUE THREAD

**Issue by GJDK** [furaiev/amazon-cognito-identity-dart-2#54]
Hi Team,

I referred the code from Use-case 19 for signing in using google account.

As a first step, I am launched to the Google Login screen(asking only email-Id). On entering the google account id and click on login, i am redirected to the error page saying "Couldn't sign you in. The browser or app may not be secure".

This is happening only in iOS and not in android.

Kindly help in sorting this out. Thanks.

**Comment by GJDK** [comment]
For reference:
![20167](https://user-images.githubusercontent.com/9714375/81140949-bd271200-8f88-11ea-9cbb-ad808709ed75.jpg)

**Comment by furaiev** [comment]
Hi @GJDK 
Pls take a look at https://stackoverflow.com/a/59673634

**Comment by GJDK** [comment]
Thanks much @furaiev
