### ISSUE TITLE
passwordless login

### ISSUE THREAD

**Issue by bitsmakerde** [furaiev/amazon-cognito-identity-dart-2#55]
Hello, everyone,

i am currently in the process of creating an app with a passwordless login. i found the following page:

[https://techinscribed.com/passwordless-phone-number-authentication-using-aws-amplify-cognito/](url)

I can also create an account with Lambda but unfortunately I can't login.

Here is my code and the error.

`Future<CognitoUserSession> signIn(String phoneNumber) async {
  final cognitoUser = new CognitoUser(phoneNumber, _userPool);
  final authDetails = new AuthenticationDetails(
    username: phoneNumber
  );
  CognitoUserSession session;
  try {
    session = await cognitoUser.authenticateUser(authDetails);
  } on CognitoUserNewPasswordRequiredException catch (e) {
    // handle New Password challenge
    print('handle New Password challenge $e');
  } on CognitoUserMfaRequiredException catch (e) {
    // handle SMS_MFA challenge
    print('SMS_MFA challenge $e');
  } on CognitoUserSelectMfaTypeException catch (e) {
    // handle SELECT_MFA_TYPE challenge
    print('SELECT_MFA_TYPE challenge $e');
  } on CognitoUserMfaSetupException catch (e) {
    // handle MFA_SETUP challenge
    print('MFA_SETUP challenge $e');
  } on CognitoUserTotpRequiredException catch (e) {
    // handle SOFTWARE_TOKEN_MFA challenge
    print('SOFTWARE_TOKEN_MFA challenge $e');
  } on CognitoUserCustomChallengeException catch (e) {
    // handle CUSTOM_CHALLENGE challenge
    print('CUSTOM_CHALLENGE challenge $e');
  } on CognitoUserConfirmationNecessaryException catch (e) {
    // handle User Confirmation Necessary
    print('User Confirmation Necessary $e');
  } on CognitoClientException catch (e) {
    // handle Wrong Username and Password and Cognito Client
    print('Wrong Username and Password and Cognito Client $e');
  } catch (e) {
    print('over error $e');
  }
  //print(session.getAccessToken().getJwtToken());
  return (session);
}`

Error

`Wrong Username and Password and Cognito Client CognitoClientException{statusCode: 400, code: InvalidParameterException, name: InvalidParameterException, message: USER_SRP_AUTH is not enabled for the client.}`

Is it possible that this type of login is not yet supported?

**Comment by furaiev** [comment]
Hi,
Actually, `USER_SRP_AUTH` is used by default. (https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/ed3071f614be25d6bbe9b42bd427ba5e99a9b480/lib/src/cognito_user.dart#L63)

I'd recommend you to start from https://medium.com/@wesselsbernd/flutter-and-aws-as-of-march-2019-1ad7f40fa9e4

**Comment by bitsmakerde** [comment]
Thank you. This is very interesting.

Is there any way to override this?

I know the link, but unfortunately the vrgabe does it without a password.

**Comment by furaiev** [comment]
You are welcome to modify the package and create a PR after testing.

**Comment by bitsmakerde** [comment]
I have now started to adjust the extension so that it works passwordless.

The first 2 steps.

1. create a user
2. generate and send the confirmation code by SMS (cognitoUser.authenticateUser())

Unfortunately, I do not know how to get ahead now.

I have tried the following login methods, but I never succeeded.

`session = await cognitoUser.sendCustomChallengeAnswer(code);`

But I need a session. If I create the user I see a session, but this is not saved in user.

`sendCustomChallengeAnswer CognitoClientException{statusCode: 400, code: InvalidParameterException, name: InvalidParameterException, message: Missing required parameter Session}`

I always see in the description that the method Auth.SignIn is used. I wanted to program it myself for the extension, but unfortunately this failed.

My idea was to do it in user_pool

` Future<CognitoUser> signInPwLess(
    String username
    ) async {
    final params = {
      'Username': username,
    };

    final data = await client.request('SignIn', params);
    if (data == null) {
      return null;
    }
    return data;
  }`

I see in main.dart a login function, but I doesn't understand how I can use.

Can you help me where I should look?

Here is my fork.

[https://github.com/bitsmakerde/amazon-cognito-identity-dart-2/tree/feature/passwordless_login](url)

Thank you

**Comment by bitsmakerde** [comment]
I have now started to adjust the extension so that it works passwordless.

The first 2 steps.

1. create a user
2. generate and send the confirmation code by SMS (cognitoUser.authenticateUser())

Unfortunately, I do not know how to get ahead now.

I have tried the following login methods, but I never succeeded.

`session = await cognitoUser.sendCustomChallengeAnswer(code);`

But I need a session. If I create the user I see a session, but this is not saved in user.

`sendCustomChallengeAnswer CognitoClientException{statusCode: 400, code: InvalidParameterException, name: InvalidParameterException, message: Missing required parameter Session}`

I always see in the description that the method Auth.SignIn is used. I wanted to program it myself for the extension, but unfortunately this failed.

Can you help me where I should look?

Here is my fork.

**Comment by furaiev** [comment]
If you have ideas on how to improve the package - welcome to contribute.
