### ISSUE TITLE
The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by Rayv1** [furaiev/amazon-cognito-identity-dart-2#57]
Hi,

i have a Problem with the Encoding and i have no clue where its coming from.

Package: 2 0.1.12+3

What iam Doing:
**Get** request against API Gateway.

code:
```
    final signedRequest = new SigV4Request(
      awsSigV4Client,
      method: 'GET',
      path: "/path/$querystring",
      headers: new Map<String, String>.from({}),
      queryParams: new Map<String, String>.from({}),
    );
    Response response;
    response = await http.get(
      signedRequest.url,
      options: Options(
        headers: signedRequest.headers,
      ),
    );
```
When i pass no special Characters it works, but as soon i pass characters like &ÄÜÖ i receive an error:
"The request signature we calculated does not match the signature you provided
The Canonical String for this request should have been
'GET
/path/%25C3%25A4 (<<< is an double encoded 'ä')
"
it seems like it is double encoded and i have no clue where to start whats going on here.

Any thoughts?

Best Regards,

**Comment by furaiev** [comment]
Hey,
I would recommend you to change umlauts with their analogs like `ae, oe, ue`.
If it isn't possible, pls check this topic https://github.com/dart-lang/http/issues/227

First of all, check what the package pass to `http` to find if this package or http package is the reason.

**Comment by furaiev** [comment]
I close this issue. Please let me know if it should be reopened.
