### ISSUE TITLE
CognitoUser.updateAttributes does not return a future

### ISSUE THREAD

**Issue by stsc3000** [furaiev/amazon-cognito-identity-dart-2#58]
Hi,

first of all: Thank you for this package, it has been working flawlessly for us :+1: 

However, we have a minor question/issue: Is there a reason for `CognitoUser.updateAttributes` and `CognitoUser.deleteAttributes` _not_ returning a `Future` of some kind (maybe `void`)?

We're trying to `await` the user attribute update before updating the UI, however Dart will show a warning `info: 'await' applied to 'void', which is not a 'Future'. (await_only_futures) ...`, although it looks like it works anyway.

Cheers

**Comment by furaiev** [comment]
Hi, @stsc3000,
Thank you for your note.

It's a good point. For sure these async methods should return Future.
We can return bool as in `deleteUser` method or Future<void>.

What is more preferable for you?

**Comment by stsc3000** [comment]
Hi @furaiev,

I do not have a strong opinion on that, but it appears to me that `Future<bool>` would be the most consistent option.
