### ISSUE TITLE
How can I get credential information for authenticated cognito identity pool?

### ISSUE THREAD

**Issue by hayashi-tz** [furaiev/amazon-cognito-identity-dart-2#59]
Dear Developer,

I have an authenticated token and identity id from the server response. 
By using that token and identity id, we can get credential information by using 
**DeveloperAuthenticatedIdentityProvider**(reference below) in both Android and iOS.

May I know how can I get credential information by using token and identity id from amazon-cognito-identity-dart-2? 

I am looking forward to your supporting soon. 

Thanks in advance!

Reference: 
https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html

**Comment by furaiev** [comment]
Hi, it isn't clear.
Do you get token via this package or somehow in another way?

**Comment by hayashi-tz** [comment]
Hi, I got authenticated token and identity id via API. But I got the way to solve my problem. I am going to use native code via flutter and native communication. So, I will close this issue. Thank you very much for supporting me.
