### ISSUE TITLE
Example with API GW not working | Missing Header

### ISSUE THREAD

**Issue by Rayv1** [furaiev/amazon-cognito-identity-dart-2#6]
Hi,

tried the example with API GW and Post Method but it was not working. I had to add an additional header with Content-Type: application/json; charset=utf-8

    final signedRequest = new SigV4Request(awsSigV4Client,
        method: 'POST',
        path: 'xx',
        headers: new Map<String, String>.from(
            {"Content-Type": "application/json; charset=utf-8"}),
        queryParams: new Map<String, String>.from({}),
        body: new Map<String, dynamic>.from({'color': 'blue'}));

Cheers

**Comment by furaiev** [comment]
Hi @Rayv1 ,
The headers are depend on your settings, there can be e.g.
`{"Content-Type": "application/graphql; charset=utf-8"}` or others, as well as it has consist additional headers.
