### ISSUE TITLE
value at 'username' failed to satisfy constraint: Member must satisfy regular expression pattern:

### ISSUE THREAD

**Issue by JoeJoe248** [furaiev/amazon-cognito-identity-dart-2#61]
I created a cognito user pool according to those instructions. I have done this numerous times. 
 Yesterday, I was able to register.  Today, I tried to login but the login screen would not render and then when I recreated the user pool I get this error for the username failing a regular expression pattern.

**Comment by furaiev** [comment]
Please share the request log details. Especially the username.
