### ISSUE TITLE
requestMFACode

### ISSUE THREAD

**Issue by GJDK** [furaiev/amazon-cognito-identity-dart-2#62]
Hi @furaiev, we enabled MFA while sign-in and we use sendMFACode method to achieve it.
Can we have an another method to request for MFA code when we intend to do some (secured) transactions/actions? 

Thanks in advance.

**Comment by furaiev** [comment]
Hi, @GJDK ,
There is no separate method for requesting a code (only sendMFACode and resendConfirmationCode).
You can try to logout the user before a secured operation or use another SMS service for getting the code.

**Comment by GJDK** [comment]
Thansk @furaiev . Closing this issue.
