### ISSUE TITLE
Null credentials when authenticated

### ISSUE THREAD

**Issue by salvatore373** [furaiev/amazon-cognito-identity-dart-2#63]
After authenticating and using the Cognito credentials for a little time (along with other AWS services), when I try to retrieve them after an app hot restart, I get the following error and I'm no more able to use them to access the other AWS services.

`Failed assertion: line 27 pos 12: 'accessKey != null': is not true.`

However, I noticed that the `getAwsCredentials()` method gets called twice: while the first time it returns null keys and tokens, the second time they are correct. If I hot reload after the hot restart that gets me null keys, I get valid keys and tokens at the first call.
I am pretty new to this package, so I might be making mistakes in my code, even though it is very basic. Here it is:

```
Future<CognitoCredentials> getCredentials() async {
    if (_cognitoUser == null || _session == null) return null;

    _credentials = CognitoCredentials(_identityPoolId, _userPool);
    await _credentials.getAwsCredentials(_session.getIdToken().getJwtToken());
    return _credentials;
}
```

Am I wrong with my code or is there an error in the package?

**Comment by furaiev** [comment]
Have you checked that your `getCredentials` isn't called twice?
This part of your code seems correct.

**Comment by salvatore373** [comment]
Yes, @furaiev, you were right. I called `getCredentials()` twice, one time immediately after the other. But why doesn't this function just return the user's credentials both the times?

**Comment by furaiev** [comment]
@salvatore373 what do you expect calling `getAwsCredentials` ?

**Comment by salvatore373** [comment]
In my opinion, whenever you call `getAwsCredentials` it should return the credentials when they're available, and when they aren't it should return a null value or throw an exception. I think that this method should never return an object with null properties.

**Comment by furaiev** [comment]
`getAwsCredentials` is a VOID method. It doesn't return data.
