### ISSUE TITLE
get user group

### ISSUE THREAD

**Issue by rodrigocorrea** [furaiev/amazon-cognito-identity-dart-2#66]
How can I get the group or grups a user belongs to

**Comment by maciejkozuch** [comment]
Hi,

I did not check this. 

List of groups should be in the "cognito:groups" claim of the ID token. Please check `CognitoUserSession:getIdToken()`.

You can check if `CognitoUser:getUserAttributes()` returns an attribute with name "cognito:groups".

**Comment by rodrigocorrea** [comment]
Hi
Thanks a lot, Yes I can access groups this way:
Map<String, dynamic> payLoad = _session.getIdToken().decodePayload();
List<dynamic> groups = payLoad['cognito:groups'];

But CognitoUser:getUserAttributes() does not return cognito:groups

Thanks a lot

**Comment by furaiev** [comment]
@rodrigocorrea `CognitoUser:getUserAttributes` returns `UserAttributes`.
If there are missed `cognito:groups` then AWS doesn't return them.
