### ISSUE TITLE
'User Confirmation Necessary' Exception for user already confirmed

### ISSUE THREAD

**Issue by NassB** [furaiev/amazon-cognito-identity-dart-2#67]
When I tried your example with 2 existing users that I have in my pool (the 2 users are already with 'Enabled / CONFIRMED' status in Cognito), I got the CognitoUserConfirmationNecessaryException but I don't understand why this exception is thrown. And the same when I tried in my app. And the variable challengeName is null when I check it in the exception. 

This is my code :

```
final cognitoUser = CognitoUser(_username, userPool, storage: userPool.storage);
final authDetails = AuthenticationDetails(
      username: _username,
      password: _password,
 );

CognitoUserSession session;

try {
     session = await cognitoUser.authenticateUser(authDetails);
} on CognitoUserConfirmationNecessaryException catch (e) {
     print(e.challengeName); -> null
     print(e.message); -> User Confirmation Necessary
     print(e.signInUserSession.isValid()); -> true
} catch (e) {
     print(e);
}
```

**Comment by furaiev** [comment]
The `CognitoUserConfirmationNecessaryException` is thrown because AWS returns `dataConfirm.UserConfirmationNecessary: true`.
This error doesn't contain key `challengeName`.

**Comment by NassB** [comment]
Ok thank you.
