### ISSUE TITLE
Use SigV4Request for signed request for Lex service 

### ISSUE THREAD

**Issue by primemb** [furaiev/amazon-cognito-identity-dart-2#68]
I use this package to signed my http request for amazon lex service like this :

```
AwsSigV4Client client=AwsSigV4Client(
      kAccessKey,
      kSecretKey,
      'https://runtime.lex.us-east-1.amazonaws.com',
      region: 'us-east-1',
      serviceName: 'lex',
    );

final signedRequest = new SigV4Request(
      client,
      method: 'POST',
      path: '/bot/MyBotName/alias/BETA/user/MyUser/text',
      body: new Map<String, dynamic>.from({"inputText": "hi"}),
    );

var response = await http.post(
      signedRequest.url,
      headers: signedRequest.headers,
      body: signedRequest.body,
    );
    print(response.body.toString());
```
but i got this message from server :
`{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}`

also i cant see : 
`X-Amz-Content-Sha256`
in headers .
am i miss something ?

**Comment by furaiev** [comment]
Where do you get `kAccessKey` and `kSecretKey`?
Don't you use headers in the `signedRequest`?

**Comment by primemb** [comment]
> Where do you get `kAccessKey` and `kSecretKey`?
they just some `consts` in my config file and i get valid response on postman with them .
> Don't you use headers in the `signedRequest`?
no i didn't what should i pass to it ?

**Comment by furaiev** [comment]
show your full postman request

**Comment by primemb** [comment]
```
POST /bot/AudioPhysicianAssistant/alias/BETA/user/pd12345/text HTTP/1.1
Host: runtime.lex.us-east-1.amazonaws.com
X-Amz-Content-Sha256: beaead3198f7da1e70d03ab969765e0821b24fc913697e929e726aeaebf0eba3
X-Amz-Date: 20200622T083559Z
Authorization: AWS4-HMAC-SHA256 Credential=MYASSESSKEY/20200622/us-east-1/lex/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=b5e4fc0a87a0d0e0041e8bc814aac277b486fe4e4d9379348b2f8b4781e4f881
Content-Type: application/json

{"inputText": "hi"}
```
if you want check it on postman please give me your email address so i can send you secretkey and accessId i cant post them in public

**Comment by furaiev** [comment]
So you have at least Authorization and Content-Type headers that aren't provided :)
Pls take a look at Use case 17 in Readme.

**Comment by primemb** [comment]
i changed my code like this : 

```
AwsSigV4Client client=AwsSigV4Client(
      kAccessKey,
      kSecretKey,
      'https://runtime.lex.us-east-1.amazonaws.com',
      region: 'us-east-1',
      serviceName: 'lex',
    );

final signedRequest = new SigV4Request(
      client,
      method: 'POST',
      path: '/bot/MyBotName/alias/BETA/user/MyUser/text',
      headers: new Map<String, String>.from({
        'Content-Type': 'application/json',
        'ACCEPT': 'application/json',
      }),
      body: new Map<String, dynamic>.from({"inputText": "hi"}),
    );

var response = await http.post(
      signedRequest.url,
      headers: signedRequest.headers,
      body: signedRequest.body,
    );
```
i print `signedRequest.headers` this is the out put:

`{Content-Type: application/json, ACCEPT: application/json, Accept: application/json, x-amz-date: 20200622T105256Z, Authorization: AWS4-HMAC-SHA256 Credential=MYASSESSKEY/20200622/us-east-1/lex/aws4_request, SignedHeaders=accept;accept;content-type;host;x-amz-date, Signature=ae4c7ac20ce8c680636bad8184dd0c9917e4e4d3340c16f3582ca84f42d4de04}`

the only thing is miss here is `X-Amz-Content-Sha256` and i think this is payload hash right ? how can i make that hash ?

**Comment by furaiev** [comment]
Try to change:
```
headers: new Map<String, String>.from(
          {'Content-Type': 'application/json; charset=utf-8'}),
```

**Comment by primemb** [comment]
> Try to change:
> 
> ```
> headers: new Map<String, String>.from(
>           {'Content-Type': 'application/json; charset=utf-8'}),
> ```

that's work thank you so much, you saved my day
