### ISSUE TITLE
Not really an issue, more like a feature request: AWS Pinpoint

### ISSUE THREAD

**Issue by metafounder** [furaiev/amazon-cognito-identity-dart-2#69]
Hi, 

Great work with the project so far, I just wanna suggest that one of the items on the product roadmap could be: AWS Pinpoint. 

Have a great day,
Cristian

**Comment by jcblancomartinez** [comment]
Hi,

@metafounder I guess you are referring to adding support for AnalyticsMetadata request parameter to multiple operations (InitiateAuth, RespondToAuthChallenge, SignUp, ConfirmSignUp, ForgotPassword, ConfirmForgotPassword)

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#CognitoUserPools-InitiateAuth-request-AnalyticsMetadata

@furaiev could you please share if you are planning to cover this any time soon?

Thanks.

**Comment by furaiev** [comment]
Hi @jcblancomartinez ,
Unfortunately, I don't have time for adding new features for now but you always can create a PR.
