### ISSUE TITLE
Respond to auth challenge SELECT_MFA_TYPE

### ISSUE THREAD

**Issue by bharathiselvan** [furaiev/amazon-cognito-identity-dart-2#71]
Hi,
Is there any way that i can respond to auth challenge SELECT_MFA_TYPE?.. I was trying to reuse sendCustomChallengeAnswer method, but the challengeName is hardcoded as 'CUSTOM_CHALLENGE'. 
Can you please provide a method that accepts both the challenge name and answer?.. This way, in future we can support any type of auth challenges.  

Thank you

**Comment by furaiev** [comment]
Hi,
This method is absent for now. I'm not sure if I have a time for its implementation nearest time, so you are welcome to implement it and make a PR.

Here is a method in JS amplify - https://github.com/aws-amplify/amplify-js/blob/e85640a4e18fa1d55411038fee58919ad73121fa/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1961

**Comment by bharathiselvan** [comment]
Okay .. Thanks for your comments ..
