### ISSUE TITLE
"Sign in with Apple" Sheet shows `null` as the app name. 

### ISSUE THREAD

**Issue by vmadupu9** [furaiev/amazon-cognito-identity-dart-2#74]
As i am trying to sign in with apple everything work fine but i see that app name is displaying `null` in the apple native sheet.

In mobile when users apple account is already signed in device settings.
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-14 at 17 22 24](https://user-images.githubusercontent.com/67674262/87669237-43cb4d00-c78b-11ea-9801-acb4167cafe7.png)

There are some open issues in other js packages. 
https://developer.apple.com/forums/thread/129899
https://github.com/aws-amplify/amplify-js/issues/4580

Please fix the issue in this package . Thanks in advance

**Comment by furaiev** [comment]
@vmadupu9 you are welcome to fix it and create a PR to this package.

**Comment by vmadupu9** [comment]
Thank you for that , i will definitely give a try . Before that i want to understand if this issue is faced by others who are using this package. Have you faced the same issue @furaiev ?

**Comment by furaiev** [comment]
I don't use Apple sign in for now.

**Comment by vmadupu9** [comment]
Okay , i will do some investigation regarding this issue.

**Comment by kbokarius** [comment]
This was an issue on Cognito's side and should be resolved now.
