### ISSUE TITLE
Social Login storing into preferences issue.

### ISSUE THREAD

**Issue by vrijmetse** [furaiev/amazon-cognito-identity-dart-2#76]
If I look at the sample code which uses normal login (email and password) I notice that the preferences got stored during

`_cognitoUser.authenticateUser(authDetails);` where the authDetails consist of email and password.

How can I authenticateUser for social login ?

Here is my code for social login

 ```
Future<User> loginSocial(String authCode) async {
    String url =
        "https://somewebsite/oauth2/token?grant_type=authorization_code&client_id=" +
            "someid" +
            "&code=" +
            authCode +
            "&redirect_uri=myapp://";
    final response = await http.post(url,
        body: {},
        headers: {'Content-Type': 'application/x-www-form-urlencoded'});
    if (response.statusCode != 200) {
      throw Exception("Received bad status code from Cognito for auth code:" +
          response.statusCode.toString() +
          "; body: " +
          response.body);
    }

    final tokenData = json.decode(response.body);

    final idToken = new CognitoIdToken(tokenData['id_token']);
    final accessToken = new CognitoAccessToken(tokenData['access_token']);
    final refreshToken = new CognitoRefreshToken(tokenData['refresh_token']);
    final session = new CognitoUserSession(idToken, accessToken,
        refreshToken: refreshToken);
    _cognitoUser = new CognitoUser(null, _userPool, signInUserSession: session, storage: _userPool.storage);

   final attributes = await _cognitoUser.getUserAttributes();
    for (CognitoUserAttribute attribute in attributes) {
      if (attribute.getName() == "email") {
        _cognitoUser.username = attribute.getValue();
        break;
      }
    }
// How do I store the current info into prefers so that the next time I open up the app I can be logged in automatically ?
//    _cognitoUser.authenticateUser(authDetails);
    return User.fromUserAttributes(attributes);
  }
```

**Comment by vrijmetse** [comment]
After looking at the code I can solve this using `await _cognitoUser.cacheTokens();` Thank you for the awesome library!

**Comment by jqr91** [comment]
Hi, i got always this response:

` Received bad status code from Cognito for auth code:400; body: {"error":"invalid_client"}`

Any solution?

Thanks

**Comment by furaiev** [comment]
@jqr91 firstly check the clientID that will be using is for OAUTH2. Not the Web, or Android clientID credentials that you have generated on project credentials.

**Comment by jqr91** [comment]
The url with clientID is this:

`String url = "https://${cognitoPoolUrl}" +
        ".amazoncognito.com/oauth2/token?grant_type=authorization_code&client_id=" +
        "${cognitoAppId}&code=" + authCode + "&redirect_uri=myapp://";`

**Comment by furaiev** [comment]
I would recommend you to go through https://github.com/aws-amplify/amplify-js/search?q=invalid_client&type=issues
