### ISSUE TITLE
[FR] support decode verify jwt 

### ISSUE THREAD

**Issue by thanhbinh84** [furaiev/amazon-cognito-identity-dart-2#77]
In order to prevent from man-in-the-middle attack, we want to decode and verify jwt to make sure the connection is secure. Is this possible to add it in our library? 

Reference link: https://github.com/awslabs/aws-support-tools/tree/master/Cognito/decode-verify-jwt

**Comment by furaiev** [comment]
@thanhbinh84 it's possible for sure, you are welcome to create PR to this repo.

**Comment by thanhbinh84** [comment]
@furaiev the sample code is written in python and ts that I am not familiar with :(

**Comment by furaiev** [comment]
You don't need to translate python to dart, you can use e.g. [Jose package](https://pub.dev/packages/jose) based on comments in python code.

**Comment by thanhbinh84** [comment]
I have managed to verify jwt token: 

```
Future<String> getJwtToken() async {
    var encodedJwt = _session.getAccessToken().getJwtToken();

    // decode the jwt
    var jwt = JsonWebToken.unverified(encodedJwt);
    printf('claims: ${jwt.claims}');

    // create key store to verify the signature
    var keyStore = JsonWebKeyStore()
      ..addKey(JsonWebKey.fromJson({
// Get JWKS from https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json
// There are 2 keys, try one by one. 
        });

    var verified = await jwt.verify(keyStore);
    return verified ? encodedJwt : null;
  }
```
The full instruction: https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html
The verification lib: https://pub.dev/packages/jose

The idea is whenever client retrieve a jwt token, we need to verify the jwt token is valid before communicating with sever to avoid man-in-the-middle attack hence improve our app security.
