### ISSUE TITLE
using cognitoUser.initAuth(userdetails) send otp in session

### ISSUE THREAD

**Issue by AshwaniSharma123** [furaiev/amazon-cognito-identity-dart-2#80]
using cognitoUser.initAuth(userdetails) send otp in session on mobile number while verifying OTP it throws an exception
flutter: CognitoClientException{statusCode: 400, code: NotAuthorizedException, name: NotAuthorizedException, message: User cannot be confirmed. Current status is CONFIRMED}

**Comment by furaiev** [comment]
It seems like you try to confirm the already confirmed user. Pls add more details what do you send.
