### ISSUE TITLE
Example - Login don't work on Web

### ISSUE THREAD

**Issue by maurobotta** [furaiev/amazon-cognito-identity-dart-2#81]
Hi

I have compiled your Example ( 4 buttons: Sign up...login ... ) , when i press on Login button example show a empty form ( no edit )

Sign Up work fine

Flutter (Channel beta, 1.20.0-7.2.pre, on Microsoft Windows [Versione 10.0.18363.959], locale it-IT)

**Comment by furaiev** [comment]
Pls debug it and share details

**Comment by maurobotta** [comment]
Add.... on Android phone work fine, i can to see 2 / 3 edit , on chome i see a empty form with back button

**Comment by littlekid440** [comment]
you need to edit pubspec.yaml with updated shared_preference
shared_preferences: ^0.5.6
