### ISSUE TITLE
CognitoUserPool.getCurrentUser() returns user with no session attached

### ISSUE THREAD

**Issue by oysterpack** [furaiev/amazon-cognito-identity-dart-2#82]
I would expect that if the user is authenticated, then the current user should be associated with a session. The current implementation never associates a session:

```dart
Future<CognitoUser> getCurrentUser() async {
    final lastUserKey =
        'CognitoIdentityServiceProvider.$_clientId.LastAuthUser';

    final lastAuthUser = await storage.getItem(lastUserKey);
    if (lastAuthUser != null) {
      return CognitoUser(lastAuthUser, this,
          storage: storage,
          clientSecret: _clientSecret,
          deviceName: _userAgent);
    }

    return null;
  }
```

**Comment by furaiev** [comment]
Correct, CognitoUserPool doesn't contain session while CognitoUser does.

**Comment by oysterpack** [comment]
I solved the problem ... in order to restore the session, tokens need to be cached, e.g., 
```dart
    final cognitoUser = CognitoUser(
      userEmail,
      userPool,
      storage: userPool.storage,
    );

    final authDetails = AuthenticationDetails(
      username: userEmail,
      password: password,
    );
    await cognitoUser.authenticateUser(authDetails);
    // in order to restore the session later on, the session tokens need to be cached into CognitoStorage
    await cognitoUser.cacheTokens(); 

    final currentUser = await userPool.getCurrentUser();
    final currentSession = await currentUser.getSession();
    expect(currentSession.isValid(), isTrue);
```

**Comment by adrianjagielak** [comment]
This should be documented or at least included in the example, I just lost hours debugging while the answer was just a single line of code.

**Comment by pal** [comment]
How come this is not default behaviour @furaiev? Do you know?

Seems like it would make a lot of sense to always persist/cache all persistable data if a Storage mechanism is in place?

**Comment by adrianjagielak** [comment]
Update from my experience from the latest non null safety version: this is only neede for non-web platforms, on web it precaches the tokens automatically (tested on web, macOS, and iOS).

**Comment by furaiev** [comment]
@pal this package is based on https://github.com/aws-amplify/amplify-js
I'm not sure why this is not the default behavior in the official package.
