### ISSUE TITLE
 I tried use case 3 (API Gateway & Lambda) and got the following error message. (Solved in the following way)

### ISSUE THREAD

**Issue by Jungho-Cheon** [furaiev/amazon-cognito-identity-dart-2#83]
The error message was as follows
"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. ...".

The source code is the same as yesterday, but errors have occurred and I confirm that the hash results of "String to Sign" are different. The content-type of the header used as the input value was modified as follows: "application/json; charset=utf-8"
If you receive a "forbidden" response from a subsequent message, you can activate the CORS.

Thank you for reading my poor English and I hope you save time if you are in the same situation as me.

**Comment by furaiev** [comment]
It seems like the same issue was described below:
https://github.com/furaiev/amazon-cognito-identity-dart-2/issues/68
