### ISSUE TITLE
Login by token

### ISSUE THREAD

**Issue by lain-ke** [furaiev/amazon-cognito-identity-dart-2#84]
So In my app, the user logs in through a `WebView` and then, it passes the tokens (_IdToken_, _AccessToken_ and _RefreshToken_) and the _username_ to the client. As seen In this plugin, on login, it writes some key values: 

> CognitoIdentityServiceProvider.[appId].[username].idToken
> CognitoIdentityServiceProvider.[appId].[username].accessToken
> CognitoIdentityServiceProvider.[appId].[username].refreshToken
> CognitoIdentityServiceProvider.[appId].[username].clockDrift
> CognitoIdentityServiceProvider.[appId].LastAuthUser

I managed to save those values manually, but when calling `_userService.checkAuthenticated()` the plugin returns `false`.

Is there any way to manually input the tokens?
Thanks in advance.

**Comment by furaiev** [comment]
It isn't currently supported. You are welcome to create a method that will manage the outside tokens and create a PR.
