### ISSUE TITLE
Error in DynamoDB connection

### ISSUE THREAD

**Issue by littlekid440** [furaiev/amazon-cognito-identity-dart-2#85]
In order to connect to DynamoDB you need to pass in header eg. 'x-amz-target': 'DynamoDB_20120810.Query'

Passing that header fails with the error message "_The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details._"

my code sample
`AwsSigV4Client(credentials.accessKeyId,
            credentials.secretAccessKey, dynamodb_endpoint,
            serviceName: "dynamodb",
            region: cognito_region,
            sessionToken: credentials.sessionToken);`

`MySigV4Request(awsSigV4Client,
        method: 'POST',
        path: '',
        headers: new Map<String, String>.from({
          'x-amz-target': 'DynamoDB_20120810.Query',
        }),
        body: new Map<String, dynamic>.from({
          "KeyConditionExpression": "AnimalType = :v1",
          "ExpressionAttributeValues": {
            ":v1": {"S": "Dog"}
          },
          "TableName": "Pets"
        }));`

**Comment by furaiev** [comment]
Try to expand headers with
```
'Content-Type': 'application/graphql; charset=utf-8'
```

**Comment by littlekid440** [comment]
No luck - adding that results in a 404. 
BTW this isn't appsync/graphQL - I'm trying to connect directly to DynamoDB at dynamodb.us-east-1.amazonaws.com

**Comment by furaiev** [comment]
I would recommend you switch to https://github.com/aws-amplify/amplify-flutter

**Comment by littlekid440** [comment]
Unfortunately my app is more of a web app and web is currently not supported with Amplify
