### ISSUE TITLE
Any way to get a JWT token for identity pool ?

### ISSUE THREAD

**Issue by moioo91120** [furaiev/amazon-cognito-identity-dart-2#86]
Hello,

On all the example, we get a JWT token with a cognito user.
On my case, I authenticate the user directly with social provider (facebook, google etc), but I still wish to get a JWT token to access service through a API Gateway JWT authorizer.

What I am trying to achieve is 
- to use https://pub.dev/packages/graphql_flutter 
- On a lambda backend with custom graphql 

And to do that, we have 2 choices : 
1) Sign all request with the sigv4 in this package (which works really fine for get/post request)
2) Or get a JWT token and pass it in the graphql_flutter package.

The first one works, but I would like to do the JWT token.

Any help is appreciated !

**Comment by furaiev** [comment]
Hi,
Have you tried this example?
https://github.com/furaiev/amazon-cognito-identity-dart-2#get-aws-credentials-with-facebook

**Comment by moioo91120** [comment]
Yes, that is what I did.

But it seems to be a session token, where I would need a JWT token for the authorizer to work.
Same JWT token that we would get with signup method

**Comment by moioo91120** [comment]
FYI, i also contacted AWS on this issue.
They said that identity provider doesn't issue a jwt token , so it's a problem on aws side
