### ISSUE TITLE
Sign up fails, missing email attribute

### ISSUE THREAD

**Issue by fgarciaDev** [furaiev/amazon-cognito-identity-dart-2#89]
Sign up fails with the following error:
`Attributes did not conform to the schema: email: the attribute is required`

Using the example app, main.dart:

```
  Future<User> signUp(String email, String password, String name) async {
    CognitoUserPoolData data;
    final userAttributes = [
      AttributeArg(name: 'name', value: name),
    ];
    data =
        await _userPool.signUp(email, password, userAttributes: userAttributes);
```

I can clearly see the email, password and userAttributes with "name" are passed in to `signUp` here. It is triggering an exception caught by the caller:
```
class _SignUpScreenState extends State<SignUpScreen> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  User _user = User();
  final userService = UserService(userPool);

  void submit(BuildContext context) async {
    _formKey.currentState.save();

    String message;
    bool signUpSuccess = false;
    try {
      _user = await userService.signUp(_user.email, _user.password, _user.name);
      signUpSuccess = true;
      message = 'User sign up successful!';
    } on CognitoClientException catch (e) {
      if (e.code == 'UsernameExistsException' ||
```

**Comment by fgarciaDev** [comment]
Just noticed in `cognito_user_pool.dart` there is no `email` attribute in the signup params.

**Comment by furaiev** [comment]
I would recommend you switch to https://github.com/aws-amplify/amplify-flutter

**Comment by nyck33** [comment]
This package actually worked for me when I created user and identity pools using Amplify but then choosing email rather than username.  This time around I chose username and now getting this error.  There does not seem to be a way to change that now except redo with amplify delete.

**Comment by nyck33** [comment]
Yes, I can confirm that choosing email in the Amplify setup steps rather than username then getting all the secrets will make this package work.  I just tried it with a fresh amplify init.
