### ISSUE TITLE
Crash when authenticating user with USER_PASSWORD_AUTH auth flow

### ISSUE THREAD

**Issue by adasiewiczr** [furaiev/amazon-cognito-identity-dart-2#91]
My app keeps crashing when I try to call `user.authenticateUser(authDetails);` with `USER_PASSWORD_AUTH` auth flow. 
After debugging I found the problem - `_authenticateUserPlainUsernamePassword()` method doesn't handle `NEW_PASSWORD_REQUIRED` challenge and that causes app crash with the following stack trace:
`E/flutter (  464): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (  464): Receiver: null
E/flutter (  464): Tried calling: []("IdToken")
E/flutter (  464): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (  464): #1      CognitoUser.getCognitoUserSession (package:amazon_cognito_identity_dart_2/src/cognito_user.dart:339:46)
E/flutter (  464): #2      CognitoUser._authenticateUserInternal (package:amazon_cognito_identity_dart_2/src/cognito_user.dart:114:9)
E/flutter (  464): #3      CognitoUser._authenticateUserPlainUsernamePassword (package:amazon_cognito_identity_dart_2/src/cognito_user.dart:530:12)
E/flutter (  464): <asynchronous suspension>
E/flutter (  464): #4      CognitoUser.authenticateUser (package:amazon_cognito_identity_dart_2/src/cognito_user.dart:471:20)
E/flutter (  464): #5      CognitoSessionService.login (package:ursila_driver/data/session/cognito_session_service.dart:31:27)
E/flutter (  464): #6      _LoginEmailPage.build.<anonymous closure> (package:ursila_driver/feature/login/email/login_email_page.dart:77:26)
E/flutter (  464): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (  464): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (  464): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (  464): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (  464): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (  464): #12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
E/flutter (  464): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
E/flutter (  464): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
E/flutter (  464): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (  464): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (  464): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (  464): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (  464): #19     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (  464): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (  464): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (  464): #22     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter (  464): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
`

**Comment by furaiev** [comment]
I would recommend you switch to https://github.com/aws-amplify/amplify-flutter

**Comment by adasiewiczr** [comment]
Would be great, but they don't support federated sign yet :(

**Comment by furaiev** [comment]
You are welcome to create a PR.
