### ISSUE TITLE
Amplify Flutter doesn't completely replace this package

### ISSUE THREAD

**Issue by hacker1024** [furaiev/amazon-cognito-identity-dart-2#94]
> Official package is available - Amplify Flutter
This repo will be archived

The official package is actually a Flutter plugin, and it can't be used for non-Flutter Dart projects.
As this package can, it's still very useful to me and probably many others.

I'm not asking for the package to still be maintained if it wasn't going to be, but is it possible the decision to archive the repository could be rethought?
That way, discussion could still happen in the issues section, and pull requests could still be made.

**Comment by furaiev** [comment]
Ok, makes sense
