### ISSUE TITLE
Exception types in CognitoUser.getSession()?

### ISSUE THREAD

**Issue by hacker1024** [furaiev/amazon-cognito-identity-dart-2#95]
In `CognitoUser.getSession()`, [generic `Exception`s are thrown](https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/a4a01273e828467580b560d5950bcd614628c139/lib/src/cognito_user.dart#L200). To differentiate between them, operations need to be done on the output from `toString()`, which isn't great.

Could these be changed to dedicated object for each cause?

**Comment by furaiev** [comment]
For sure it can be. You are welcome to create a PR.
