### ISSUE TITLE
Hi,faild upload s3

### ISSUE THREAD

**Issue by kazumasamatsumoto** [furaiev/amazon-cognito-identity-dart-2#96]
Hi,
Please check this working code https://gist.github.com/furaiev/e0fff973b31babd36f5c5d7b53d85349

_Originally posted by @furaiev in https://github.com/furaiev/amazon-cognito-identity-dart-2/issue_comments/641844250_

try this

Flutter log is 
UploadS3 success {"message":"Missing Authentication Token"}

but S3 bucket refresh 
don't upload image

please help me

**Comment by springyuniverse** [comment]
same here

**Comment by furaiev** [comment]
I think you should try to use your own credentials.
