### ISSUE TITLE
Unable to verify Secret Hash for client

### ISSUE THREAD

**Issue by Rayv1** [furaiev/amazon-cognito-identity-dart-2#99]
Hi,

is a App Client Secret still supported?

I have a App Client with Client Secret and added it to User Pool:
```
CognitoUserPool _userPool = new CognitoUserPool(
    cognitoUserPoolId, cognitoClientId,
    clientSecret: clientSecret);
```
but cant get it to work.

Sign In Function
```

  Future<User> iOSSignIn(String email, String password) async {
    _cognitoUser = new CognitoUser(
      email,
      _userPool,
    );

    final authDetails = new AuthenticationDetails(
      username: email,
      password: password,
    );

    bool isConfirmed;
    try {
      _cognitoUserSession = await _cognitoUser.authenticateUser(authDetails);
      isConfirmed = true;
    } on CognitoClientException catch (e) {
      if (e.code == 'UserNotConfirmedException') {
        isConfirmed = false;
      } else {
        return null;
      }
    }

    if (!_cognitoUserSession.isValid()) {
      return null;
    }

    final attributes = await _cognitoUser.getUserAttributes();
    final user = new User.fromUserAttributes(attributes);
    user.confirmed = isConfirmed;
    user.hasAccess = true;

    return user;
  }
```
For me it seems iam not doing something special here, just following the docs, but still getting: "Unable to verify Secret Hash for client xxxxx"

Any Ideas?

P.s: iam already using the Amplify Package but its more than 1 year far from this Package, so for iOS there the authentication is not returning a valid Session Token.

**Comment by chirag729** [comment]
Try passing the clientSecret when creating your CognitoUser

`_cognitoUser = new CognitoUser(
      email,
      _userPool,
      clientSecret: _clientSecret
    );`

**Comment by GuilhermeVendramini** [comment]
Same problem here, even adding clientSecret.

**Comment by vuchau** [comment]
Sample problem here with version **0.1.21**

**Comment by furaiev** [comment]
@vuchau samples are outdated. I'll appreciate it if someone can refresh them.

**Comment by vuchau** [comment]
@furaiev I follow guide from https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js#user-content-configuration and success.

**Comment by devpascoe** [comment]
hmmm same issue here. Any clues?
